# Generated by Django 5.2.14 on 2026-05-31 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0015_cmsembedwidget_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsblock",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("hero", "Hero Banner"),
                    ("rich_text", "Rich Text"),
                    ("faq_list", "FAQ List"),
                    ("link_list", "Link List"),
                    ("cta_group", "CTA Buttons"),
                    ("image_text", "Image + Text"),
                    ("notice", "Notice / Callout"),
                    ("contact_info", "Contact Info"),
                    ("section_group", "Section Group"),
                    ("table", "Data Table"),
                    ("numbered_list", "Numbered List"),
                    ("proposal_cards", "Proposal Cards"),
                    ("navigation_grid", "Navigation Grid"),
                    ("sponsor_year", "Sponsor Year"),
                    ("embed", "Embed (iframe)"),
                    ("embed_widget", "Embed CMS Widget"),
                    ("frozen_page", "Frozen Page (imported)"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="FrozenPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "source_url",
                    models.URLField(
                        help_text="The external page URL to capture.", max_length=2000
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Defaults to the source page's <title>.",
                        max_length=300,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier (kebab-case).",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "frozen_html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The captured self-contained HTML document.",
                    ),
                ),
                (
                    "remove_header",
                    models.BooleanField(
                        default=False,
                        help_text="Strip page headers / banners on import.",
                    ),
                ),
                (
                    "remove_nav",
                    models.BooleanField(
                        default=False,
                        help_text="Strip navigation bars / menus on import.",
                    ),
                ),
                (
                    "remove_footer",
                    models.BooleanField(
                        default=False, help_text="Strip page footers on import."
                    ),
                ),
                (
                    "remove_cookie_consent",
                    models.BooleanField(
                        default=False,
                        help_text="Strip cookie / consent banners on import.",
                    ),
                ),
                (
                    "remove_ads",
                    models.BooleanField(
                        default=False,
                        help_text="Strip ad / advertisement blocks on import.",
                    ),
                ),
                (
                    "extra_remove_selectors",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Extra CSS selectors to remove, one per line (e.g. '.newsletter-popup').",
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the document was last captured.",
                        null=True,
                    ),
                ),
                (
                    "byte_size",
                    models.PositiveIntegerField(
                        default=0, help_text="Size of the captured document in bytes."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "Frozen Page",
                "verbose_name_plural": "Frozen Pages",
                "db_table": "cms_frozenpage",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="cms_frozenp_slug_890fb0_idx"),
                    models.Index(
                        fields=["status"], name="cms_frozenp_status_01d3cb_idx"
                    ),
                ],
            },
        ),
    ]
