# Generated by Django 5.2.14 on 2026-06-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0015_cmsembedwidget_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsblock",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("hero", "Hero Banner"),
                    ("rich_text", "Rich Text"),
                    ("faq_list", "FAQ List"),
                    ("link_list", "Link List"),
                    ("cta_group", "CTA Buttons"),
                    ("image_text", "Image + Text"),
                    ("notice", "Notice / Callout"),
                    ("contact_info", "Contact Info"),
                    ("section_group", "Section Group"),
                    ("table", "Data Table"),
                    ("project_table", "Project Table (searchable)"),
                    ("numbered_list", "Numbered List"),
                    ("proposal_cards", "Proposal Cards"),
                    ("navigation_grid", "Navigation Grid"),
                    ("sponsor_year", "Sponsor Year"),
                    ("embed", "Embed (iframe)"),
                    ("embed_widget", "Embed CMS Widget"),
                ],
                max_length=30,
            ),
        ),
    ]
