# Generated by Django 5.2.10 on 2026-08-04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0018_sync_page_projects_controls_stylesheet"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteRedirect",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "source_path",
                    models.CharField(
                        help_text="Exact legacy path. It cannot be changed after this redirect is created.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "destination_path",
                    models.CharField(
                        help_text="A published CMS page or registered public application route.",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text=(
                            "Enable this permanent 301 redirect after reviewing it carefully. "
                            "Browsers and search engines may cache a 301 for a long time."
                        ),
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "edge_sync_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("synced", "Synced"), ("failed", "Failed")],
                        db_index=True,
                        default="pending",
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("edge_sync_error", models.TextField(blank=True, default="", editable=False)),
                ("edge_sync_attempted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("edge_synced_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "edge_rule_managed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        help_text="Internal marker that a confirmed CMS-managed Amplify rule still owns this source.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route Redirect",
                "verbose_name_plural": "Route Redirects",
                "db_table": "cms_routeredirect",
                "ordering": ["source_path"],
                "indexes": [
                    models.Index(
                        fields=["destination_path", "is_active"],
                        name="cms_routere_destina_beb591_idx",
                    )
                ],
            },
        ),
    ]
