# Generated by Django 5.2.17 on 2026-10-01 04:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0019_route_redirect"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # A nullable column without a default: PostgreSQL adds it without rewriting the table. No index on purpose:
        # nothing filters on it (the statistics count COALESCE(visitor_id, ip_address), an expression), and building
        # one here would hold an ACCESS EXCLUSIVE lock on the largest write-heavy table for the whole build.
        migrations.AddField(
            model_name="pageview",
            name="visitor_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
