MODEL_MAP = {
    "Member": ("authn.models", "Member"),
    "ContactEmail": ("authn.models", "ContactEmail"),
    "ContactPhone": ("authn.models", "ContactPhone"),
    "Event": ("event.models", "Event"),
    "EventRegistration": ("event.models", "EventRegistration"),
    "Ticket": ("event.models", "Ticket"),
    "CheckIn": ("event.models", "CheckIn"),
    "CheckInRecord": ("event.models", "CheckInRecord"),
    "Project": ("projects.models", "Project"),
    "Semester": ("projects.models", "Semester"),
    "EmailCampaign": ("mail.models", "EmailCampaign"),
    "RecipientLog": ("mail.models", "RecipientLog"),
    "CMSPage": ("cms.models", "CMSPage"),
    "CMSBlock": ("cms.models", "CMSBlock"),
    "NewsArticle": ("cms.models", "NewsArticle"),
    "NewsFeedSource": ("cms.models", "NewsFeedSource"),
    "PageView": ("cms.models", "PageView"),
    "Menu": ("cms.models", "Menu"),
}

ALLOWED_QUERY_FIELDS = {
    "Member": {
        "id",
        "first_name",
        "last_name",
        "organization",
        "title",
        "is_staff",
        "is_active",
        "created_at",
        "updated_at",
    },
    "ContactEmail": {"id", "email_address", "email_type", "verified", "subscribe", "created_at", "updated_at"},
    "ContactPhone": {"id", "phone_number", "phone_type", "verified", "created_at", "updated_at"},
    "Event": {"id", "name", "slug", "date", "location", "is_live", "created_at", "updated_at"},
    "EventRegistration": {
        "id",
        "attendee_first_name",
        "attendee_last_name",
        "attendee_email",
        "attendee_organization",
        "attendee_title",
        "created_at",
        "updated_at",
    },
    "Ticket": {"id", "name", "price", "capacity", "created_at", "updated_at"},
    "CheckIn": {"id", "name", "created_at", "updated_at"},
    "CheckInRecord": {"id", "timestamp", "created_at", "updated_at"},
    "Project": {
        "id",
        "project_title",
        "team_name",
        "team_number",
        "class_code",
        "organization",
        "industry",
        "student_names",
        "created_at",
        "updated_at",
    },
    "Semester": {"id", "year", "season", "label", "is_published", "created_at", "updated_at"},
    "EmailCampaign": {
        "id",
        "name",
        "subject",
        "status",
        "audience_type",
        "total_recipients",
        "sent_count",
        "failed_count",
        "sent_at",
        "created_at",
        "updated_at",
    },
    "RecipientLog": {"id", "status", "error_message", "created_at", "updated_at"},
    "CMSPage": {
        "id",
        "title",
        "slug",
        "route",
        "status",
        "meta_description",
        "published_at",
        "created_at",
        "updated_at",
    },
    "CMSBlock": {"id", "block_type", "sort_order", "created_at", "updated_at"},
    "NewsArticle": {
        "id",
        "title",
        "source",
        "author",
        "source_url",
        "published_at",
        "summary",
        "created_at",
        "updated_at",
    },
    "NewsFeedSource": {"id", "name", "feed_url", "is_active", "created_at", "updated_at"},
    "PageView": {"id", "path", "timestamp", "ip_address", "created_at"},
    "Menu": {"id", "name", "display_name", "is_active", "created_at", "updated_at"},
}

SAFE_LOOKUPS = frozenset(
    {
        "exact",
        "iexact",
        "contains",
        "icontains",
        "in",
        "gt",
        "gte",
        "lt",
        "lte",
        "startswith",
        "istartswith",
        "endswith",
        "iendswith",
        "range",
        "date",
        "year",
        "month",
        "day",
        "week_day",
        "hour",
        "minute",
        "second",
        "isnull",
        "regex",
        "iregex",
    }
)
