[uwsgi]
chdir = /var/www/i2g-double-mail
module = wsgi:app

processes = 1
threads = 2

plugin = python3
#virtualenv = /var/www/myapp/myenv

master = true
#socket = /var/www/i2g-double-mail/wsgi.sock
#socket = /tmp/wsgi.sock
socket = localhost:5000
chmod-socket = 666
vacuum = true

die-on-term = true
