# Generated by Django 5.2.10 on 2026-09-16 03:42

from django.db import migrations, models


def disable_auto_sync_on_inactive_schedules(apps, schema_editor):
    """Auto-sync used to be honoured only for the active schedule.

    ``sync_schedule`` now syncs every schedule whose auto-sync is enabled, so a
    previously-active row that still carries the flag would silently start
    being rewritten from its (possibly repurposed) sheet. Reset it once here;
    admins opt archived years back in deliberately.
    """
    Schedule = apps.get_model("event", "CurrentProjectSchedule")
    Schedule.objects.filter(is_active=False, auto_sync_enabled=True).update(auto_sync_enabled=False)


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0010_active_schedule_invariant"),
    ]

    operations = [
        migrations.RunPython(disable_auto_sync_on_inactive_schedules, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="currentprojectschedule",
            name="auto_sync_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Automatically sync this schedule from its Google Sheet on a schedule (applies to every schedule, not only the active one — switch it off for archived years).",
                verbose_name="Auto Sync",
            ),
        ),
    ]
