# Generated by Django 5.2.17 on 2026-09-23 19:46

from django.db import migrations, models


def preserve_existing_phone_requirement(apps, schema_editor):
    Event = apps.get_model("event", "Event")
    Event.objects.using(schema_editor.connection.alias).filter(verify_phone=True).update(require_phone=True)


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0011_currentprojectschedule_auto_sync_help_text"),
    ]

    operations = [
        # Reconcile the temporary migration state with the physical expand-phase
        # schema from 0008 before SQLite rebuilds Event for the new constraints.
        # No production contract migration has removed the legacy column or
        # materialized the non-null end date and date-range constraint yet.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(model_name="event", name="event_end_date_gte_start_date"),
                migrations.AlterField(
                    model_name="event",
                    name="end_date",
                    field=models.DateField(null=True, verbose_name="End date"),
                ),
                migrations.AddField(
                    model_name="event",
                    name="is_live",
                    field=models.BooleanField(default=False, db_default=False),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name="event",
            name="require_phone",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Require registrants to provide a phone number.",
                verbose_name="Require phone number",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="require_secondary_email",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Require registrants to provide a secondary email address.",
                verbose_name="Require secondary email",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="verify_secondary_email",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Require verification when a secondary email address is provided.",
                verbose_name="Verify secondary email if provided",
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="secondary_email_verified",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.RunPython(preserve_existing_phone_requirement, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="event",
            name="allow_secondary_email",
            field=models.BooleanField(
                default=False,
                help_text="Show the secondary email field on the registration form.",
                verbose_name="Collect secondary email",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="collect_phone",
            field=models.BooleanField(
                default=False,
                help_text="Show the phone number field on the registration form.",
                verbose_name="Collect phone number",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="verify_phone",
            field=models.BooleanField(
                default=False,
                help_text="Require SMS verification when a phone number is provided.",
                verbose_name="Verify phone if provided",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("collect_phone", True), ("require_phone", False), _connector="OR"),
                name="event_require_phone_requires_collect",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allow_secondary_email", True),
                    ("verify_secondary_email", False),
                    _connector="OR",
                ),
                name="event_verify_email_requires_collect",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allow_secondary_email", True),
                    ("require_secondary_email", False),
                    _connector="OR",
                ),
                name="event_require_email_requires_collect",
            ),
        ),
        # Restore current application state without prematurely contracting the
        # database. Old writers can omit every newly added field because each
        # has a persistent database default.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name="event", name="is_live"),
                migrations.AlterField(
                    model_name="event",
                    name="end_date",
                    field=models.DateField(verbose_name="End date"),
                ),
                migrations.AddConstraint(
                    model_name="event",
                    constraint=models.CheckConstraint(
                        condition=models.Q(end_date__gte=models.F("date")),
                        name="event_end_date_gte_start_date",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
