# Generated by Django 5.2.17 on 2026-09-23 23:41

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_merge_20260905_0635"),
        ("event", "0012_unified_contact_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationsheetsynclog",
            name="sync_type",
            field=models.CharField(choices=[("append", "Automatic sync"), ("full", "Manual sync")], max_length=10),
        ),
        migrations.AddField(
            model_name="registrationsheetsynclog",
            name="details",
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.CreateModel(
            name="RegistrationSheetSyncConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "sync_mode",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic"),
                            ("interval", "Batch changes at intervals"),
                            ("manual", "Manual only"),
                        ],
                        default="automatic",
                        max_length=12,
                    ),
                ),
                (
                    "debounce_seconds",
                    models.PositiveIntegerField(
                        default=15,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3600),
                        ],
                    ),
                ),
                (
                    "max_delay_seconds",
                    models.PositiveIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3600),
                        ],
                    ),
                ),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "header_row",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                ("field_settings", models.JSONField(blank=True, default=dict)),
                ("column_mappings", models.JSONField(blank=True, default=dict)),
                (
                    "requested_generation",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                (
                    "completed_generation",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                (
                    "first_dirty_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "last_dirty_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "next_sync_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("scheduled", "Scheduled"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("blocked", "Needs attention"),
                            ("failed", "Failed"),
                        ],
                        default="idle",
                        editable=False,
                        max_length=12,
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, default="", editable=False),
                ),
                (
                    "last_added_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "last_updated_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "last_unchanged_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "last_conflict_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "last_deleted_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "last_header_changes_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_sheet_sync_config",
                        to="event.event",
                    ),
                ),
                (
                    "pending_job",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.backgroundjob",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("debounce_seconds__gte", 1)),
                        name="event_sync_debounce_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_delay_seconds__gte", models.F("debounce_seconds"))),
                        name="event_sync_delay_gte_debounce",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("interval_minutes__gte", 1)),
                        name="event_sync_interval_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("header_row__gte", 1)),
                        name="event_sync_header_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "completed_generation__lte",
                                models.F("requested_generation"),
                            )
                        ),
                        name="event_sync_generation_order",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistrationSheetSyncRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("registration_id", models.UUIDField()),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_sheet_records",
                        to="event.event",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "registration_id"),
                        name="event_sheet_registration_receipt_unique",
                    )
                ],
            },
        ),
    ]
