# Generated by Django 5.2.17 on 2026-09-05 07:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0018_phone_challenge_verified_grants"),
    ]

    operations = [
        migrations.CreateModel(
            name="SendDestinationState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("destination_kind", models.CharField(db_index=True, max_length=8)),
                ("destination_normalized", models.CharField(max_length=254)),
                ("last_reserved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("destination_kind", "destination_normalized"),
                        name="authn_send_destination_state_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SendQuotaWindow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("destination_hourly", "Destination hourly"),
                            ("sms_daily", "SMS daily"),
                        ],
                        max_length=32,
                    ),
                ),
                ("scope_key", models.CharField(max_length=254)),
                ("window_started_at", models.DateTimeField()),
                ("reserved_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["kind", "scope_key", "window_started_at"],
                        name="authn_sendq_kind_ef955e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "scope_key", "window_started_at"),
                        name="authn_send_quota_window_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SendVerificationChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("operation", models.CharField(db_index=True, max_length=64)),
                (
                    "destination_kind",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Phone")], max_length=8
                    ),
                ),
                (
                    "destination_normalized",
                    models.CharField(db_index=True, max_length=254),
                ),
                (
                    "principal_type",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("session", "Session"),
                            ("anonymous", "Anonymous"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "principal_key",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("algorithm", models.CharField(max_length=32)),
                ("cost", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("consumed", "Consumed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "context_fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"],
                        name="authn_sendv_status_becf60_idx",
                    ),
                    models.Index(
                        fields=["operation", "destination_normalized", "status"],
                        name="authn_sendv_operati_aea185_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SendVerificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("request_id", models.UUIDField(unique=True)),
                ("operation", models.CharField(db_index=True, max_length=64)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")], max_length=8
                    ),
                ),
                ("destination_kind", models.CharField(max_length=8)),
                (
                    "destination_normalized",
                    models.CharField(db_index=True, max_length=254),
                ),
                ("principal_type", models.CharField(max_length=16)),
                (
                    "principal_key",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("request_fingerprint", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("provider_accepted", "Provider accepted"),
                            ("definitely_failed", "Definitely failed"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("quota_reserved", models.BooleanField(default=False)),
                ("reserved_at", models.DateTimeField(blank=True, null=True)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                ("http_status", models.PositiveIntegerField(default=202)),
                (
                    "client_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "otp_challenge_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("idempotency_expires_at", models.DateTimeField(db_index=True)),
                (
                    "challenge",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="send_request",
                        to="authn.sendverificationchallenge",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "destination_kind",
                            "destination_normalized",
                            "quota_reserved",
                            "reserved_at",
                        ],
                        name="authn_send_req_dest_quota_idx",
                    ),
                    models.Index(
                        fields=["channel", "quota_reserved", "reserved_at"],
                        name="authn_sendv_channel_5bea16_idx",
                    ),
                    models.Index(
                        fields=["status", "idempotency_expires_at"],
                        name="authn_sendv_status_ad2b67_idx",
                    ),
                ],
            },
        ),
    ]
