# Generated by Django 5.2.17 on 2026-09-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authn", "0019_senddestinationstate_sendquotawindow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailauthchallenge",
            name="context_identifier",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="Business context that must match when verifying or consuming this challenge.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="emailauthchallenge",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("login", "Login"),
                    ("password_reset", "Password Reset"),
                    ("password_change", "Password Change"),
                    ("account_delete", "Account Delete"),
                    ("contact_email_verify", "Contact Email Verify"),
                    ("event_registration", "Event Registration"),
                    ("admin_login", "Admin Login"),
                ],
                max_length=32,
            ),
        ),
    ]
