# Generated by Django 5.2.17 on 2026-10-02 04:41

from django.db import migrations, models
from django.db.models import Exists, OuterRef


def mark_pending_registrations(apps, schema_editor):
    """Flag existing unfinished self-service signups as pending.

    Before this field every inactive member counted as a pending registration, which let an
    admin-deactivated account reactivate itself through the email-code flow. Only members that
    look like an abandoned signup are flagged: inactive, never staff, never logged in, no verified
    contact, issued at least one REGISTER challenge and never verified/consumed any challenge
    (completing a registration consumes one). Every other inactive member stays not-pending.
    """
    Member = apps.get_model("authn", "Member")
    ContactEmail = apps.get_model("authn", "ContactEmail")
    ContactPhone = apps.get_model("authn", "ContactPhone")
    EmailAuthChallenge = apps.get_model("authn", "EmailAuthChallenge")

    member_ref = OuterRef("pk")
    (
        Member.objects.filter(is_active=False, is_staff=False, is_superuser=False, last_login__isnull=True)
        .filter(Exists(EmailAuthChallenge.objects.filter(member_id=member_ref, purpose="register")))
        .exclude(Exists(EmailAuthChallenge.objects.filter(member_id=member_ref, status__in=("verified", "consumed"))))
        .exclude(Exists(ContactEmail.objects.filter(member_id=member_ref, verified=True)))
        .exclude(Exists(ContactPhone.objects.filter(member_id=member_ref, verified=True)))
        .update(registration_pending=True)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("authn", "0020_event_email_challenge_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="registration_pending",
            field=models.BooleanField(
                db_default=False,
                default=False,
                editable=False,
                help_text="Self-service registration not yet completed. Cleared once the member is first activated.",
                verbose_name="Registration pending",
            ),
        ),
        migrations.RunPython(mark_pending_registrations, migrations.RunPython.noop),
    ]
