# Generated by Django 5.2.17 on 2026-09-30 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0020_event_email_challenge_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginFailureWindow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("identifier_digest", models.CharField(max_length=64)),
                (
                    "window",
                    models.CharField(
                        choices=[
                            ("15m", "15 minutes"),
                            ("24h", "24 hours"),
                            ("5m", "5 minutes (all identifiers)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("window_index", models.BigIntegerField()),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("identifier_digest", "window", "window_index"),
                        name="authn_login_failure_window_unique",
                    )
                ],
            },
        ),
    ]
