# Generated by Django 5.2.10 on 2026-08-13 13:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_deliveryratelimit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailserviceconfig",
            old_name="ses_from_name",
            new_name="from_name",
        ),
        migrations.RenameField(
            model_name="emailserviceconfig",
            old_name="ses_max_send_rate",
            new_name="max_send_rate",
        ),
        migrations.RenameField(
            model_name="emailserviceconfig",
            old_name="ses_from_email",
            new_name="from_email",
        ),
        migrations.AlterField(
            model_name="emailserviceconfig",
            name="from_email",
            field=models.CharField(
                blank=True,
                default="i2g@g.ucmerced.edu",
                help_text="Sender email address used for outgoing email.",
                max_length=254,
                verbose_name="From Email",
            ),
        ),
        migrations.AddField(
            model_name="emailserviceconfig",
            name="provider",
            field=models.CharField(
                choices=[("ses", "AWS SES"), ("smtp", "SMTP")],
                default="ses",
                help_text="Email delivery provider used by this configuration.",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="SMTPProviderConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(default="Default", max_length=128, verbose_name="Config Name"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one SMTP provider config can be active. Activating this will deactivate others.",
                        verbose_name="Active",
                    ),
                ),
                ("host", models.CharField(max_length=254, verbose_name="SMTP Host")),
                (
                    "port",
                    models.PositiveIntegerField(default=587, verbose_name="SMTP Port"),
                ),
                ("use_tls", models.BooleanField(default=True, verbose_name="Use TLS")),
                ("use_ssl", models.BooleanField(default=False, verbose_name="Use SSL")),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="SMTP Username",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="SMTP Password",
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(default=30, verbose_name="Connection Timeout (seconds)"),
                ),
            ],
            options={
                "verbose_name": "SMTP Provider Config",
                "verbose_name_plural": "SMTP Provider Configs",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="core_one_active_smtp_provider_config",
                    )
                ],
            },
        ),
    ]
