# Generated by Django 5.2.17 on 2026-09-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_deliveryratelimit"),
    ]

    operations = [
        migrations.CreateModel(
            name="SendVerificationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Default", max_length=128, verbose_name="Config Name"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one config can be active. Activating this will deactivate others.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("observe", "Observe (proofs optional)"),
                            ("enforce", "Enforce (proofs required)"),
                            ("pause", "Pause protected sends"),
                        ],
                        default="observe",
                        help_text="Pause fails closed. Enforce requires a valid proof. Observe logs missing proofs.",
                        max_length=16,
                    ),
                ),
                (
                    "hmac_secret",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Current ALTCHA challenge signing secret. Rotate by moving this value to Previous.",
                        max_length=255,
                        verbose_name="HMAC secret",
                    ),
                ),
                (
                    "hmac_key_secret",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional fast-path key-signing secret for PoW v2 deterministic verification.",
                        max_length=255,
                        verbose_name="HMAC key secret",
                    ),
                ),
                (
                    "hmac_secret_previous",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Retained during rotation so in-flight challenges still verify.",
                        max_length=255,
                        verbose_name="Previous HMAC secret",
                    ),
                ),
                (
                    "hmac_key_secret_previous",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Previous HMAC key secret",
                    ),
                ),
                ("key_version", models.PositiveIntegerField(default=1)),
                (
                    "algorithm",
                    models.CharField(default="PBKDF2/SHA-256", max_length=32),
                ),
                (
                    "cost",
                    models.PositiveIntegerField(
                        default=5000,
                        help_text="PBKDF2 iteration cost. Clients cannot lower this; it is signed server-side.",
                    ),
                ),
                ("challenge_ttl_seconds", models.PositiveIntegerField(default=300)),
                ("destination_hourly_limit", models.PositiveIntegerField(default=10)),
                (
                    "destination_cooldown_seconds",
                    models.PositiveIntegerField(default=60),
                ),
                (
                    "sms_daily_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Channel-wide SMS reservation cap per UTC day. Leave empty until calibrated.",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Send Verification Config",
                "verbose_name_plural": "Send Verification Configs",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="core_one_active_send_verification_config",
                    )
                ],
            },
        ),
    ]
