# Generated by Django 5.2.17 on 2026-09-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_rename_ses_from_name_emailserviceconfig_from_name_and_more"),
        ("core", "0030_sendverificationconfig"),
    ]

    operations = []
