# Generated by Django 5.2.10 on 2026-03-09 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "email",
                    models.EmailField(
                        help_text="Delegated Gmail address (e.g. i2g@g.ucmerced.edu)",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Sender display name (e.g. "Innovate to Grow")',
                        max_length=128,
                    ),
                ),
                (
                    "service_account_json",
                    models.TextField(
                        help_text="Full service account JSON key from Google Cloud Console"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only one account can be active at a time.",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last time this account was used for a Gmail API call.",
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Last error message from Gmail API.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gmail API Account",
                "verbose_name_plural": "Gmail API Accounts",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("send", "Send"),
                            ("reply", "Reply"),
                            ("forward", "Forward"),
                            ("read", "Read"),
                            ("delete", "Delete"),
                            ("label", "Label"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                (
                    "gmail_message_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=500)),
                (
                    "recipients",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comma-separated list of recipients.",
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mail_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="mail.googleaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "status"],
                        name="mail_emaill_action_6a970c_idx",
                    ),
                    models.Index(
                        fields=["account", "created_at"],
                        name="mail_emaill_account_15b034_idx",
                    ),
                ],
            },
        ),
    ]
