# Generated by Django 5.2.12 on 2026-04-02 21:44

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0002_remove_event_version_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Internal campaign name.", max_length=200
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Email subject line. Use {{first_name}}, {{last_name}}, or {{full_name}} for personalization.",
                        max_length=998,
                    ),
                ),
                (
                    "body",
                    django_ckeditor_5.fields.CKEditor5Field(
                        help_text="Email body. Use {{first_name}}, {{last_name}}, or {{full_name}} for personalization.",
                        verbose_name="default",
                    ),
                ),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("subscribers", "All Email Subscribers"),
                            ("event_registrants", "Event Registrants"),
                        ],
                        default="subscribers",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required when audience is 'Event Registrants'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_campaigns",
                        to="event.event",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Campaign",
                "verbose_name_plural": "Email Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecipientLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("email_address", models.EmailField(max_length=254)),
                (
                    "recipient_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=16)),
                ("error_message", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_logs",
                        to="mail.emailcampaign",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipient Log",
                "verbose_name_plural": "Recipient Logs",
                "ordering": ["-sent_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "email_address"),
                        name="unique_campaign_recipient",
                    )
                ],
            },
        ),
    ]
