# Generated by Django 5.2.12 on 2026-04-02 23:10

import django.db.models.deletion
import mail.models.magic_login
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailcampaign",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Amazon SES Mail",
                "verbose_name_plural": "Amazon SES Mails",
            },
        ),
        migrations.AddField(
            model_name="emailcampaign",
            name="manual_emails",
            field=models.TextField(
                blank=True,
                default="",
                help_text="One email per line. Used when audience is 'Manual Emails'.",
            ),
        ),
        migrations.AddField(
            model_name="emailcampaign",
            name="selected_members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Pick members when audience is 'Selected Members'.",
                related_name="selected_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emailcampaign",
            name="audience_type",
            field=models.CharField(
                choices=[
                    ("subscribers", "All Email Subscribers"),
                    ("event_registrants", "Event Registrants"),
                    ("selected_members", "Selected Members"),
                    ("manual", "Manual Emails"),
                ],
                default="subscribers",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="emailcampaign",
            name="subject",
            field=models.CharField(max_length=998),
        ),
        migrations.CreateModel(
            name="MagicLoginToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=mail.models.magic_login.default_expiry
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("is_used", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_tokens",
                        to="mail.emailcampaign",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magic_login_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
