# Generated by Django 5.2.10 on 2026-03-10 08:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_ses_sender(apps, schema_editor):
    SESAccount = apps.get_model("mail", "SESAccount")

    if SESAccount.objects.filter(is_deleted=False).exists():
        return

    SESAccount.objects.create(
        email="i2g@g.ucmerced.edu",
        display_name="Innovate to Grow",
        is_active=True,
    )


def remove_default_ses_sender(apps, schema_editor):
    SESAccount = apps.get_model("mail", "SESAccount")
    SESAccount.objects.filter(email="i2g@g.ucmerced.edu").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SESAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "email",
                    models.EmailField(
                        default="i2g@g.ucmerced.edu",
                        help_text="Fixed SES sender identity used by the new I2G system.",
                        max_length=254,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="Innovate to Grow",
                        help_text='Sender display name (for example "Innovate to Grow").',
                        max_length=128,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to temporarily block SES sends from the admin.",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last time this SES sender successfully attempted a send.",
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Last SES error encountered during send.",
                    ),
                ),
            ],
            options={
                "verbose_name": "SES Mail Sender",
                "verbose_name_plural": "SES Mail Senders",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SESEmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "action",
                    models.CharField(choices=[("send", "Send")], default="send", max_length=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                (
                    "ses_message_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=500)),
                (
                    "recipients",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comma-separated list of recipients.",
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="mail.sesaccount",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ses_mail_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SES Email Log",
                "verbose_name_plural": "SES Email Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="mail_sesema_status_676f62_idx",
                    ),
                    models.Index(
                        fields=["account", "created_at"],
                        name="mail_sesema_account_9f0a04_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(create_default_ses_sender, remove_default_ses_sender),
    ]
