# Generated by Django 5.2.12 on 2026-04-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_alter_emailcampaign_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcampaign",
            name="member_email_scope",
            field=models.CharField(
                choices=[
                    ("primary", "Primary email only"),
                    ("all", "All emails (primary + secondary)"),
                ],
                default="primary",
                help_text="Send to primary email only, or all emails for each member.",
                max_length=16,
                verbose_name="Send to",
            ),
        ),
    ]
