# Generated by Django 5.2.12 on 2026-04-02 23:22

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_emailcampaign_member_email_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Email Content"),
        ),
        migrations.AlterField(
            model_name="emailcampaign",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
