# Generated by Django 5.2.10 on 2026-03-21 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0003_backfill_ses_logs_into_email_logs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sesemaillog",
            name="bounce_subtype",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="sesemaillog",
            name="bounce_type",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="sesemaillog",
            name="complaint_feedback_type",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="sesemaillog",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("delivered", "Delivered"),
                    ("bounced", "Bounced"),
                    ("complained", "Complained"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="sesemaillog",
            name="delivery_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="sesemaillog",
            index=models.Index(
                fields=["ses_message_id"], name="mail_sesema_ses_mes_e05eec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sesemaillog",
            index=models.Index(
                fields=["delivery_status", "created_at"],
                name="mail_sesema_deliver_db4c90_idx",
            ),
        ),
    ]
