# Generated by Django 5.2.12 on 2026-04-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0004_alter_emailcampaign_body_alter_emailcampaign_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="body",
            field=models.TextField(
                blank=True, default="", verbose_name="Email Content"
            ),
        ),
    ]
