# Generated by Django 5.2.10 on 2026-03-05 18:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "source",
                    models.CharField(db_index=True, default="ucmerced", max_length=100),
                ),
                ("source_guid", models.CharField(max_length=500, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("source_url", models.URLField(max_length=1000)),
                ("summary", models.TextField(blank=True, default="")),
                ("image_url", models.URLField(blank=True, default="", max_length=1000)),
                ("author", models.CharField(blank=True, default="", max_length=255)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("raw_payload", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "source_guid"],
                        name="news_newsar_source_11826b_idx",
                    )
                ],
            },
        ),
    ]
