# Generated by Django 5.2.10 on 2026-03-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
