# Generated by Django 5.2.10 on 2026-03-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_newsarticle_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="hero_caption",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="hero_image_url",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
    ]
