# Generated by Django 5.2.10 on 2026-03-05 22:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_newsarticle_hero_caption_newsarticle_hero_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsFeedSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("name", models.CharField(max_length=200)),
                ("feed_url", models.URLField(max_length=1000)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_created", models.PositiveIntegerField(default=0)),
                ("last_sync_updated", models.PositiveIntegerField(default=0)),
                ("last_sync_errors", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
