# Generated by Django 5.2.10 on 2026-03-05 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_newsfeedsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsfeedsource",
            name="source_key",
            field=models.SlugField(default="ucmerced", max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="NewsSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("duration_seconds", models.FloatField(default=0)),
                ("articles_created", models.PositiveIntegerField(default=0)),
                ("articles_updated", models.PositiveIntegerField(default=0)),
                ("errors_text", models.TextField(blank=True, default="")),
                (
                    "feed_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="news.newsfeedsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
