# Generated by Django 5.2.10 on 2026-03-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_newsfeedsource_source_key_newssynclog"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="newssynclog",
            index=models.Index(
                fields=["feed_source", "-started_at"],
                name="news_synclog_source_started",
            ),
        ),
    ]
