SYSTEM_INTELLIGENCE_ADK_PREFIX = "/admin/system-intelligence/adk"
SYSTEM_INTELLIGENCE_ADK_DEV_UI_PATH = f"{SYSTEM_INTELLIGENCE_ADK_PREFIX}/dev-ui/"
SYSTEM_INTELLIGENCE_ADK_LOGO_URL = f"{SYSTEM_INTELLIGENCE_ADK_PREFIX}/dev-ui/assets/ADK-512-color.svg"
SYSTEM_INTELLIGENCE_ADK_RUNTIME_DIRNAME = "system-intelligence-adk"
