# Generated by Django 5.2.10 on 2026-01-30 01:43

import django.db.models.deletion
import notify.models.unsubscribe
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")],
                        help_text="Notification channel (email or SMS).",
                        max_length=10,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        help_text="Email address or phone number notified.",
                        max_length=255,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject for email notifications.",
                        max_length=255,
                    ),
                ),
                ("message", models.TextField(help_text="Notification body content.")),
                (
                    "provider",
                    models.CharField(
                        default="console",
                        help_text="Provider used to send the notification.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Delivery status.",
                        max_length=10,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if delivery failed."
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was sent.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "target"],
                        name="notify_noti_channel_92eae0_idx",
                    ),
                    models.Index(
                        fields=["status"], name="notify_noti_status_177b43_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="notify_noti_created_3f9cba_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Unsubscribe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")],
                        help_text="Channel the recipient opted out from.",
                        max_length=10,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        help_text="Email address or phone number that opted out.",
                        max_length=255,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        default="general",
                        help_text="Logical scope/list this unsubscribe applies to.",
                        max_length=64,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Optional reason provided for the unsubscribe.",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=notify.models.unsubscribe.default_metadata,
                        help_text="Optional structured details captured during unsubscribe.",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Token that can be used to confirm or revert the unsubscribe.",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unsubscribe",
                "verbose_name_plural": "Unsubscribes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "target"], name="notify_unsub_target_idx"
                    ),
                    models.Index(fields=["token"], name="notify_unsub_token_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel", "target", "scope"),
                        name="notify_unsub_unique_target_scope",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")],
                        help_text="Verification channel (email or SMS).",
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("code", "Code"), ("link", "Link")],
                        help_text="Verification delivery method (code or link).",
                        max_length=10,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        help_text="Email address or phone number to verify.",
                        max_length=255,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        default="contact_verification",
                        help_text="Purpose of the verification (e.g., contact_verification).",
                        max_length=64,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Verification code when method is code.",
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Verification token when method is link.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Expiration timestamp for this verification request."
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of verification attempts made."
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=5, help_text="Maximum allowed verification attempts."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the verification request.",
                        max_length=16,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when verification succeeded.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Request",
                "verbose_name_plural": "Verification Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "target", "method", "purpose"],
                        name="notify_veri_channel_02ce99_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="notify_veri_expires_b27333_idx"
                    ),
                    models.Index(
                        fields=["status"], name="notify_veri_status_a656da_idx"
                    ),
                    models.Index(fields=["code"], name="notify_veri_code_4a392f_idx"),
                    models.Index(fields=["token"], name="notify_veri_token_6f540b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BroadcastMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name so admins can identify this broadcast.",
                        max_length=128,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")],
                        help_text="Delivery channel for this broadcast.",
                        max_length=10,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        default="general",
                        help_text="Audience scope/list that should receive this broadcast.",
                        max_length=64,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject line for email broadcasts.",
                        max_length=255,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Body of the broadcast message (HTML allowed for email)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        help_text="Lifecycle status of this broadcast.",
                        max_length=16,
                    ),
                ),
                (
                    "total_recipients",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total subscribers targeted when the broadcast was sent.",
                    ),
                ),
                (
                    "sent_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of recipients successfully sent."
                    ),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of recipients that failed to send."
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, help_text="Last error captured while sending."
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when sending completed.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Broadcast Message",
                "verbose_name_plural": "Broadcast Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel"], name="notify_broadcast_channel_idx"
                    ),
                    models.Index(fields=["status"], name="notify_broadcast_status_idx"),
                    models.Index(fields=["scope"], name="notify_broadcast_scope_idx"),
                ],
            },
        ),
    ]
