# Generated by Django 5.2.10 on 2026-02-03 12:45

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessageLayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique key used by the code to select this template.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this email template.",
                        max_length=128,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description to help admins understand this template.",
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        help_text="Django template string for the email subject.",
                        max_length=255,
                    ),
                ),
                (
                    "preheader_template",
                    models.CharField(
                        blank=True,
                        help_text="Optional preheader text shown in email clients.",
                        max_length=255,
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="Django template string for the email body (HTML allowed)."
                    ),
                ),
                (
                    "default_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default JSON context merged into every render.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active templates are used for sending.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Message Layout",
                "verbose_name_plural": "Email Message Layouts",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["key"], name="notify_email_key_idx"),
                    models.Index(fields=["is_active"], name="notify_email_active_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailMessageContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Label for this context set (e.g. 'Member Preview').",
                        max_length=128,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description for this context set.",
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON data merged into the template context.",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this context as the default preview data.",
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contexts",
                        to="notify.emailmessagelayout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Message Context",
                "verbose_name_plural": "Email Message Contexts",
                "ordering": ["name"],
                "unique_together": {("layout", "name")},
            },
        ),
    ]
