# Generated by Django 4.2.11 on 2025-12-26 13:02

from django.db import migrations, models
import notify.models.unsubscribe
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unsubscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")],
                        help_text="Channel the recipient opted out from.",
                        max_length=10,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        help_text="Email address or phone number that opted out.",
                        max_length=255,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        default="general",
                        help_text="Logical scope/list this unsubscribe applies to.",
                        max_length=64,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Optional reason provided for the unsubscribe.",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=notify.models.unsubscribe.default_metadata,
                        help_text="Optional structured details captured during unsubscribe.",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Token that can be used to confirm or revert the unsubscribe.",
                        unique=True,
                    ),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the unsubscribe was recorded.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unsubscribe",
                "verbose_name_plural": "Unsubscribes",
                "ordering": ["-unsubscribed_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "target"], name="notify_unsub_target_idx"
                    ),
                    models.Index(fields=["token"], name="notify_unsub_token_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="unsubscribe",
            constraint=models.UniqueConstraint(
                fields=("channel", "target", "scope"),
                name="notify_unsub_unique_target_scope",
            ),
        ),
    ]
