# Generated by Django 5.2.10 on 2026-02-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="googlegmailaccount",
            old_name="password",
            new_name="google_app_password",
        ),
    ]
