# Generated by Django 4.2.11 on 2025-12-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="notify_noti_channel_92eae0_idx",
            old_name="notify_not_channel_3e606a_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="notify_noti_status_177b43_idx",
            old_name="notify_not_status_644f4f_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="notify_noti_created_3f9cba_idx",
            old_name="notify_not_created_0c1841_idx",
        ),
        migrations.RenameIndex(
            model_name="verificationrequest",
            new_name="notify_veri_channel_02ce99_idx",
            old_name="notify_ver_channel_852b93_idx",
        ),
        migrations.RenameIndex(
            model_name="verificationrequest",
            new_name="notify_veri_expires_b27333_idx",
            old_name="notify_ver_expires_69207a_idx",
        ),
        migrations.RenameIndex(
            model_name="verificationrequest",
            new_name="notify_veri_status_a656da_idx",
            old_name="notify_ver_status_85f9c4_idx",
        ),
        migrations.RenameIndex(
            model_name="verificationrequest",
            new_name="notify_veri_code_4a392f_idx",
            old_name="notify_ver_code_a71fa5_idx",
        ),
        migrations.RenameIndex(
            model_name="verificationrequest",
            new_name="notify_veri_token_6f540b_idx",
            old_name="notify_ver_token_84684c_idx",
        ),
    ]
