# Generated by Django 5.2.10 on 2026-02-03 12:46

from django.db import migrations


def seed_templates(apps, schema_editor):
    EmailMessageLayout = apps.get_model("notify", "EmailMessageLayout")

    templates = [
        {
            "key": "verification_code",
            "name": "Verification Code Email",
            "description": "Sent when a user requests a verification code.",
            "subject_template": "Your verification code",
            "preheader_template": "Your verification code is {{ code }}",
            "body_template": (
                "<p>Hi {{ recipient_name }},</p>"
                "<p>Your verification code is: <strong>{{ code }}</strong>.</p>"
                "<p>This code expires in {{ expires_in_minutes }} minutes.</p>"
                "<p>If you did not request this, you can ignore this email.</p>"
            ),
            "default_context": {},
            "is_active": True,
        },
        {
            "key": "verification_link",
            "name": "Verification Link Email",
            "description": "Sent when a user requests a verification link.",
            "subject_template": "Verify your email",
            "preheader_template": "Verify your email address",
            "body_template": (
                "<p>Hi {{ recipient_name }},</p>"
                "<p>Please verify your email by clicking the link below:</p>"
                "<p><a href=\"{{ verification_link }}\">Verify Email</a></p>"
                "<p>This link expires in {{ expires_in_minutes }} minutes.</p>"
            ),
            "default_context": {},
            "is_active": True,
        },
    ]

    for payload in templates:
        EmailMessageLayout.objects.get_or_create(key=payload["key"], defaults=payload)


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0002_email_message_templates"),
    ]

    operations = [
        migrations.RunPython(seed_templates, migrations.RunPython.noop),
    ]
