# Generated by Django 4.2.11 on 2025-12-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0002_unsubscribe_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name so admins can identify this broadcast.",
                        max_length=128,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")],
                        help_text="Delivery channel for this broadcast.",
                        max_length=10,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        default="general",
                        help_text="Audience scope/list that should receive this broadcast.",
                        max_length=64,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject line for email broadcasts.",
                        max_length=255,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Body of the broadcast message (HTML allowed for email)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        help_text="Lifecycle status of this broadcast.",
                        max_length=16,
                    ),
                ),
                (
                    "total_recipients",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total subscribers targeted when the broadcast was sent.",
                    ),
                ),
                (
                    "sent_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of recipients successfully sent."
                    ),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of recipients that failed to send."
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, help_text="Last error captured while sending."
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when sending completed.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this broadcast was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this broadcast was last updated."
                    ),
                ),
            ],
            options={
                "verbose_name": "Broadcast Message",
                "verbose_name_plural": "Broadcast Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel"], name="notify_broadcast_channel_idx"
                    ),
                    models.Index(fields=["status"], name="notify_broadcast_status_idx"),
                    models.Index(fields=["scope"], name="notify_broadcast_scope_idx"),
                ],
            },
        ),
    ]
