# Generated by Django 5.2.10 on 2026-02-03 12:47

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0003_seed_email_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique key used to select this layout (e.g. 'base').",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this layout.",
                        max_length=128,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description to help admins understand this layout.",
                    ),
                ),
                (
                    "html_template",
                    models.TextField(
                        help_text="Django template HTML. Use {{ body_html }}, {{ subject }}, {{ brand_name }}, etc."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active layouts are used for sending.",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this layout when no specific layout is selected.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Layout",
                "verbose_name_plural": "Email Layouts",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["key"], name="notify_layout_key_idx"),
                    models.Index(fields=["is_active"], name="notify_layout_active_idx"),
                    models.Index(fields=["is_default"], name="notify_layout_default_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="emailmessagelayout",
            name="layout",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional base layout to wrap this message.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_layouts",
                to="notify.emaillayout",
            ),
        ),
    ]
