# Generated by Django 5.2.10 on 2026-02-09 22:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0005_seed_email_layout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleGmailAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "gmail_address",
                    models.CharField(
                        help_text="Google Gmail address (e.g. team@gmail.com)",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "password",
                    models.TextField(
                        help_text="Google App Password (16 characters, spaces ignored)"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Sender display name (e.g. "I2G Team")',
                        max_length=128,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to temporarily disable this account.",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as default sender. Only one account can be default.",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        default="smtp.gmail.com",
                        help_text="SMTP server hostname.",
                        max_length=128,
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(
                        default=587,
                        help_text="SMTP server port (587 for TLS, 465 for SSL).",
                    ),
                ),
                (
                    "use_tls",
                    models.BooleanField(
                        default=True,
                        help_text="Use STARTTLS (port 587). Uncheck for SSL (port 465).",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last time an email was sent from this account.",
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Last error message when sending failed.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gmail Account",
                "verbose_name_plural": "Gmail Accounts",
                "ordering": ["-is_default", "-is_active", "-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="emaillayout",
            new_name="notify_emai_key_792b31_idx",
            old_name="notify_layout_key_idx",
        ),
        migrations.RenameIndex(
            model_name="emaillayout",
            new_name="notify_emai_is_acti_e0dbb1_idx",
            old_name="notify_layout_active_idx",
        ),
        migrations.RenameIndex(
            model_name="emaillayout",
            new_name="notify_emai_is_defa_2683de_idx",
            old_name="notify_layout_default_idx",
        ),
        migrations.RenameIndex(
            model_name="emailmessagelayout",
            new_name="notify_emai_key_d68fd7_idx",
            old_name="notify_email_key_idx",
        ),
        migrations.RenameIndex(
            model_name="emailmessagelayout",
            new_name="notify_emai_is_acti_6e3b7d_idx",
            old_name="notify_email_active_idx",
        ),
        migrations.AddField(
            model_name="googlegmailaccount",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="googlegmailaccount",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
