# Generated by Django 5.2.10 on 2026-03-26 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleSheetSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "slug",
                    models.SlugField(
                        help_text="API lookup key, e.g. 'current-event', '2025-fall'",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="Display name", max_length=200)),
                (
                    "sheet_type",
                    models.CharField(
                        choices=[
                            ("current-event", "Current Event"),
                            ("past-projects", "Past Projects"),
                            ("archive-event", "Archive Event"),
                        ],
                        help_text="Controls parsing logic",
                        max_length=20,
                    ),
                ),
                (
                    "spreadsheet_id",
                    models.CharField(
                        help_text="Google Sheets spreadsheet ID", max_length=200
                    ),
                ),
                (
                    "range_a1",
                    models.CharField(
                        help_text="Sheet range, e.g. 'A1:Y76' or 'Past-Projects-WEB-LIVE'",
                        max_length=200,
                    ),
                ),
                (
                    "tracks_spreadsheet_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional separate spreadsheet for track info",
                        max_length=200,
                    ),
                ),
                (
                    "tracks_sheet_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Track info sheet name, e.g. '2025-I2G2-Tracks'",
                        max_length=200,
                    ),
                ),
                (
                    "semester_filter",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional row filter, e.g. '2025-2 Fall'",
                        max_length=100,
                    ),
                ),
                (
                    "cache_ttl_seconds",
                    models.PositiveIntegerField(
                        default=300, help_text="Cache TTL in seconds"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Disable without deleting"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sheet Source",
                "verbose_name_plural": "Sheet Sources",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="SheetsAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "email",
                    models.EmailField(
                        help_text="Service account email (e.g. sheets-sync@project.iam.gserviceaccount.com)",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Display name (e.g. "I2G Sheets Sync")',
                        max_length=128,
                    ),
                ),
                (
                    "service_account_json",
                    models.TextField(
                        help_text="Full service account JSON key from Google Cloud Console"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only one account can be active at a time.",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last time this account was used for a Sheets API call.",
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Last error message from Sheets API.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sheets API Account",
                "verbose_name_plural": "Sheets API Accounts",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SheetLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text='Human-readable label, e.g. "Fall 2025 Projects"',
                        max_length=200,
                    ),
                ),
                (
                    "spreadsheet_id",
                    models.CharField(
                        help_text="Google Sheets spreadsheet ID", max_length=200
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tab/sheet name within the spreadsheet",
                        max_length=200,
                    ),
                ),
                (
                    "range_a1",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional A1 range within the tab, e.g. 'A1:L100'",
                        max_length=100,
                    ),
                ),
                (
                    "column_mapping",
                    models.JSONField(
                        default=dict,
                        help_text='Map sheet headers to model fields. Use __ for FK fields: {"Year": "semester__year", "Class": "class_code"}. Use "__skip__" to ignore a column.',
                    ),
                ),
                (
                    "fk_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='FK behavior config: {"semester": {"create_if_missing": true, "defaults": {"is_published": true}}}',
                    ),
                ),
                (
                    "lookup_fields",
                    models.JSONField(
                        default=list,
                        help_text='Model field names forming the unique key for upserts, e.g. ["semester", "team_number", "project_title"]',
                    ),
                ),
                (
                    "sync_direction",
                    models.CharField(
                        choices=[
                            ("pull", "Pull (Sheet → DB)"),
                            ("push", "Push (DB → Sheet)"),
                            ("both", "Both (Manual choice per operation)"),
                        ],
                        default="pull",
                        max_length=4,
                    ),
                ),
                (
                    "row_transform_hook",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Dotted path to a Python function for custom row transforms before FK resolution, e.g. 'projects.services.hooks.resolve_project_row'",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Django model to sync with this sheet",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="sheets.sheetsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sheet Link",
                "verbose_name_plural": "Sheet Links",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("pull", "Pull (Sheet → DB)"),
                            ("push", "Push (DB → Sheet)"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        max_length=7,
                    ),
                ),
                ("rows_processed", models.PositiveIntegerField(default=0)),
                ("rows_created", models.PositiveIntegerField(default=0)),
                ("rows_updated", models.PositiveIntegerField(default=0)),
                ("rows_skipped", models.PositiveIntegerField(default=0)),
                ("rows_failed", models.PositiveIntegerField(default=0)),
                (
                    "error_details",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of {"row": N, "error": "..."} entries',
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sheet_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="sheets.sheetlink",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sheet_sync_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Log",
                "verbose_name_plural": "Sync Logs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["direction", "status"],
                        name="sheets_sync_directi_afae0c_idx",
                    ),
                    models.Index(
                        fields=["sheet_link", "started_at"],
                        name="sheets_sync_sheet_l_1fc256_idx",
                    ),
                ],
            },
        ),
    ]
