# Generated by Django 4.2.11 on 2025-12-31 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0005_googleaccount_googlesheet_sheet"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Sheet",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(auto_now_add=True, db_index=True),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, db_index=True),
                        ),
                        (
                            "name",
                            models.CharField(
                                help_text="Name of the sheet for internal reference.",
                                max_length=255,
                            ),
                        ),
                        (
                            "description",
                            models.TextField(
                                blank=True,
                                help_text="Optional description of what this sheet contains.",
                            ),
                        ),
                        (
                            "columns",
                            models.JSONField(
                                blank=True,
                                default=list,
                                help_text="List of column definitions. Each should have 'name' and 'key'.",
                            ),
                        ),
                        (
                            "data",
                            models.JSONField(
                                blank=True,
                                default=list,
                                help_text="List of row data matching the column keys.",
                            ),
                        ),
                        (
                            "created_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="created_sheets",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Sheet",
                        "verbose_name_plural": "Sheets",
                        "db_table": "pages_sheet",
                        "ordering": ["-updated_at"],
                    },
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_locked", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabs",
                        to="sheets.sheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tab",
                "verbose_name_plural": "Tabs",
                "ordering": ["sheet", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="SheetMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheet_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="sheets.sheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sheet Member",
                "verbose_name_plural": "Sheet Members",
                "ordering": ["sheet", "member"],
            },
        ),
        migrations.CreateModel(
            name="Row",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="sheets.tab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Row",
                "verbose_name_plural": "Rows",
                "ordering": ["tab", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("key", models.CharField(max_length=100)),
                ("column_type", models.CharField(default="text", max_length=50)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=False)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="sheets.tab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Column",
                "verbose_name_plural": "Columns",
                "ordering": ["tab", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("value", models.JSONField(blank=True, null=True)),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="sheets.column",
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="sheets.row",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cell",
                "verbose_name_plural": "Cells",
            },
        ),
        migrations.AddIndex(
            model_name="tab",
            index=models.Index(
                fields=["sheet", "position"], name="sheets_tab_sheet_pos_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tab",
            constraint=models.UniqueConstraint(
                fields=("sheet", "name"), name="sheets_tab_sheet_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="tab",
            constraint=models.UniqueConstraint(
                fields=("sheet", "position"), name="sheets_tab_sheet_pos_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="sheetmember",
            index=models.Index(fields=["sheet"], name="sheets_sheetmember_sheet_idx"),
        ),
        migrations.AddIndex(
            model_name="sheetmember",
            index=models.Index(fields=["member"], name="sheets_sheetmember_member_idx"),
        ),
        migrations.AddConstraint(
            model_name="sheetmember",
            constraint=models.UniqueConstraint(
                fields=("sheet", "member"), name="sheets_sheetmember_sheet_member_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="row",
            index=models.Index(
                fields=["tab", "position"], name="sheets_row_tab_pos_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="row",
            constraint=models.UniqueConstraint(
                fields=("tab", "position"), name="sheets_row_tab_pos_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="column",
            index=models.Index(
                fields=["tab", "position"], name="sheets_column_tab_pos_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="column",
            constraint=models.UniqueConstraint(
                fields=("tab", "key"), name="sheets_column_tab_key_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="column",
            constraint=models.UniqueConstraint(
                fields=("tab", "position"), name="sheets_column_tab_pos_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="cell",
            index=models.Index(fields=["row"], name="sheets_cell_row_idx"),
        ),
        migrations.AddIndex(
            model_name="cell",
            index=models.Index(fields=["column"], name="sheets_cell_col_idx"),
        ),
        migrations.AddConstraint(
            model_name="cell",
            constraint=models.UniqueConstraint(
                fields=("row", "column"), name="sheets_cell_row_col_uniq"
            ),
        ),
    ]
