# Generated by Django 5.2.12 on 2026-04-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="version",
        ),
        migrations.RemoveField(
            model_name="eventregistration",
            name="version",
        ),
        migrations.RemoveField(
            model_name="question",
            name="version",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="version",
        ),
    ]
