# Generated by Django 5.2.12 on 2026-04-03 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="schedule_last_synced_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="schedule_projects_gid",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="schedule_sheet_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="schedule_sync_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="event",
            name="schedule_tracks_gid",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EventScheduleSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("start_time", models.CharField(default="1:00", max_length=10)),
                ("slot_minutes", models.PositiveIntegerField(default=30)),
                (
                    "accent_color",
                    models.CharField(blank=True, default="#002856", max_length=20),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_sections",
                        to="event.event",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="EventScheduleTrack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("track_number", models.PositiveIntegerField()),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                ("room", models.CharField(blank=True, default="", max_length=255)),
                ("zoom_link", models.CharField(blank=True, default="", max_length=500)),
                ("topic", models.CharField(blank=True, default="", max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="event.eventschedulesection",
                    ),
                ),
            ],
            options={
                "ordering": ["section__display_order", "display_order", "track_number"],
            },
        ),
        migrations.CreateModel(
            name="EventScheduleSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("slot_order", models.PositiveIntegerField()),
                ("is_break", models.BooleanField(default=False)),
                (
                    "year_semester",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("class_code", models.CharField(blank=True, default="", max_length=32)),
                (
                    "team_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("team_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "project_title",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "organization",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("industry", models.CharField(blank=True, default="", max_length=100)),
                ("abstract", models.TextField(blank=True, default="")),
                ("student_names", models.TextField(blank=True, default="")),
                (
                    "name_title",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "display_text",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_schedule_slots",
                        to="projects.project",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="event.eventscheduletrack",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "track__section__display_order",
                    "track__display_order",
                    "slot_order",
                ],
            },
        ),
        migrations.CreateModel(
            name="EventAgendaItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "section_type",
                    models.CharField(
                        choices=[("expo", "Expo"), ("awards", "Awards & Reception")],
                        max_length=20,
                    ),
                ),
                ("time_label", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_items",
                        to="event.event",
                    ),
                ),
            ],
            options={
                "ordering": ["section_type", "display_order", "time_label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "section_type", "display_order"),
                        name="unique_agenda_order_per_event_section",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="eventschedulesection",
            constraint=models.UniqueConstraint(
                fields=("event", "code"), name="unique_schedule_section_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventscheduletrack",
            constraint=models.UniqueConstraint(
                fields=("section", "track_number"),
                name="unique_track_number_per_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventscheduletrack",
            constraint=models.UniqueConstraint(
                fields=("section", "display_order"),
                name="unique_track_order_per_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventscheduleslot",
            constraint=models.UniqueConstraint(
                fields=("track", "slot_order"), name="unique_slot_order_per_track"
            ),
        ),
    ]
