# Generated by Django 5.2.10 on 2026-03-17 22:31

import event.models.ticket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="barcode",
            field=models.CharField(
                default=event.models.ticket.generate_barcode,
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
    ]
