# Generated by Django 5.2.10 on 2026-03-17 23:41

import django.db.models.deletion
import event.models.registration
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_ticket_barcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "ticket_code",
                    models.CharField(
                        default=event.models.registration.generate_registration_ticket_code,
                        editable=False,
                        max_length=24,
                        unique=True,
                    ),
                ),
                (
                    "attendee_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "attendee_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "question_answers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Stored answers for event registration questions.",
                    ),
                ),
                (
                    "ticket_email_sent_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("ticket_email_error", models.TextField(blank=True, default="")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="event.event",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="event.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "created_at"],
                        name="event_event_member__27d860_idx",
                    ),
                    models.Index(
                        fields=["event", "created_at"],
                        name="event_event_event_i_5ec1f8_idx",
                    ),
                    models.Index(
                        fields=["ticket_code"], name="event_event_ticket__f78c13_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "event"),
                        name="unique_event_registration_per_member",
                    )
                ],
            },
        ),
    ]
