# Generated by Django 5.2.10 on 2026-03-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_eventregistration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date"]},
        ),
        migrations.RemoveField(
            model_name="event",
            name="time",
        ),
    ]
