# Generated by Django 5.2.10 on 2026-03-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_alter_event_options_remove_event_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="attendee_organization",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
