# Generated by Django 5.2.10 on 2026-04-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_remove_event_schedule_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="semester",
        ),
    ]
