# Generated by Django 5.2.10 on 2026-04-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_remove_event_semester"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentProject",
            fields=[],
            options={
                "verbose_name": "Current Project",
                "verbose_name_plural": "Current Projects",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("projects.project",),
        ),
    ]
