# Generated by Django 5.2.10 on 2026-03-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_eventregistration_attendee_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventregistration",
            name="attendee_name",
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="attendee_first_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="attendee_last_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
