# Generated by Django 5.2.10 on 2026-04-05

import uuid
from django.db import migrations, models


def copy_schedule_source_to_config(apps, schema_editor):
    EventScheduleSource = apps.get_model("event", "EventScheduleSource")
    CurrentProjectSchedule = apps.get_model("event", "CurrentProjectSchedule")

    source = EventScheduleSource.objects.first()
    if source and (source.sheet_id or source.tracks_gid or source.projects_gid):
        CurrentProjectSchedule.objects.create(
            sheet_id=source.sheet_id,
            tracks_gid=source.tracks_gid,
            projects_gid=source.projects_gid,
            last_synced_at=source.last_synced_at,
            sync_error=source.sync_error,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_currentproject"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentProjectSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sheet_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The ID of the Google Sheet containing project and schedule data.",
                        max_length=255,
                        verbose_name="Google Sheet ID",
                    ),
                ),
                (
                    "tracks_gid",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="The GID of the worksheet containing track definitions.",
                        null=True,
                        verbose_name="Tracks Worksheet GID",
                    ),
                ),
                (
                    "projects_gid",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="The GID of the worksheet containing project/slot data.",
                        null=True,
                        verbose_name="Projects Worksheet GID",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("sync_error", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Current Project and Schedule",
                "verbose_name_plural": "Current Project and Schedule",
            },
        ),
        migrations.RunPython(copy_schedule_source_to_config, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="eventschedulesource",
            name="event",
        ),
        migrations.DeleteModel(
            name="CurrentProject",
        ),
        migrations.DeleteModel(
            name="EventScheduleSource",
        ),
    ]
