# Generated by Django 5.2.10 on 2026-04-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_currentprojectschedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventscheduletrack",
            name="winner",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
