# Generated by Django 5.2.10 on 2026-04-05 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_eventscheduletrack_winner"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventagendaitem",
            name="unique_agenda_order_per_event_section",
        ),
        migrations.RemoveConstraint(
            model_name="eventschedulesection",
            name="unique_schedule_section_per_event",
        ),
        migrations.RemoveField(
            model_name="eventagendaitem",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventschedulesection",
            name="event",
        ),
        migrations.AddField(
            model_name="currentprojectschedule",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Event Name"
            ),
        ),
        migrations.AddField(
            model_name="eventagendaitem",
            name="config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agenda_items",
                to="event.currentprojectschedule",
            ),
        ),
        migrations.AddField(
            model_name="eventschedulesection",
            name="config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_sections",
                to="event.currentprojectschedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventagendaitem",
            constraint=models.UniqueConstraint(
                fields=("config", "section_type", "display_order"),
                name="unique_agenda_order_per_config_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventschedulesection",
            constraint=models.UniqueConstraint(
                fields=("config", "code"), name="unique_schedule_section_per_config"
            ),
        ),
    ]
