# Generated by Django 5.2.10 on 2026-04-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_decouple_schedule_from_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentprojectschedule",
            name="show_winners",
            field=models.BooleanField(
                default=False,
                help_text="Display winner data on the schedule page.",
                verbose_name="Show Winners",
            ),
        ),
    ]
