# Generated by Django 5.2.10 on 2026-03-26 07:07

import django.core.serializers.json
import django.db.models.deletion
import pages.models.pages.layout.footer_content
import pages.models.pages.layout.menu
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FooterContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name to identify this footer version",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Machine-readable key for this footer version",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        default=pages.models.pages.layout.footer_content.default_footer_content,
                        help_text="Structured JSON describing footer sections, links, and CTAs",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one footer can be active at a time",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Content",
                "verbose_name_plural": "Footer Contents",
                "db_table": "pages_footercontent",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "name",
                    models.SlugField(
                        help_text="Machine-readable name (e.g. 'main_nav', 'footer').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated from name if not provided.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this menu's purpose.",
                        null=True,
                    ),
                ),
                (
                    "items",
                    models.JSONField(
                        default=pages.models.pages.layout.menu.default_menu_items,
                        help_text="JSON array of menu items. Each item can be an external link or app route.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active menus are served to the frontend.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
                "db_table": "pages_menu",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CMSPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier for import/export. Do not change after publishing.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        help_text="Frontend route path, e.g. '/about'. Must start with '/'.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("meta_description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "page_css_class",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CSS class for the page wrapper div, e.g. 'about-page'.",
                        max_length=100,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "CMS Page",
                "verbose_name_plural": "CMS Pages",
                "db_table": "cms_cmspage",
                "ordering": ["sort_order", "title"],
                "indexes": [
                    models.Index(
                        fields=["route", "status"], name="cms_cmspage_route_08f33c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "homepage_page",
                    models.ForeignKey(
                        blank=True,
                        help_text='Published CMS page to render at "/". Leave blank to use the published "/" page.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pages.cmspage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="CMSBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Banner"),
                            ("rich_text", "Rich Text"),
                            ("faq_list", "FAQ List"),
                            ("link_list", "Link List"),
                            ("cta_group", "CTA Buttons"),
                            ("image_text", "Image + Text"),
                            ("notice", "Notice / Callout"),
                            ("contact_info", "Contact Info"),
                            ("section_group", "Section Group"),
                            ("table", "Data Table"),
                            ("numbered_list", "Numbered List"),
                            ("proposal_cards", "Proposal Cards"),
                            ("navigation_grid", "Navigation Grid"),
                        ],
                        max_length=30,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "admin_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Label shown in admin for easier identification.",
                        max_length=200,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="pages.cmspage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Block",
                "verbose_name_plural": "Content Blocks",
                "db_table": "cms_cmsblock",
                "ordering": ["sort_order"],
                "indexes": [
                    models.Index(
                        fields=["page", "sort_order"],
                        name="cms_cmsbloc_page_id_455329_idx",
                    )
                ],
            },
        ),
    ]
