# Generated by Django 5.2.10 on 2026-02-19 07:16

import django.db.models.deletion
import pages.models.media
import pages.models.pages.component.page_component
import pages.models.pages.layout.footer_content
import pages.models.pages.layout.menu
import pages.models.pages.shared.validators
import pages.models.uniforms.form
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentDataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("source_name", models.CharField(max_length=255, unique=True)),
                ("source_url", models.URLField(max_length=255)),
                (
                    "request_method",
                    models.CharField(
                        choices=[("GET", "GET"), ("POST", "POST")],
                        default="GET",
                        max_length=10,
                    ),
                ),
                (
                    "auth_mode",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("login_required", "Login Required"),
                            ("self_only", "Self Only"),
                        ],
                        default="public",
                        max_length=32,
                    ),
                ),
                ("cache_ttl_seconds", models.PositiveIntegerField(default=300)),
                ("timeout_ms", models.PositiveIntegerField(default=10000)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "response_schema_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
            ],
            options={
                "verbose_name": "Component Data Source",
                "verbose_name_plural": "Component Data Sources",
                "ordering": ["source_name"],
            },
        ),
        migrations.CreateModel(
            name="FooterContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name to identify this footer version",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Machine-readable key for this footer version",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        default=pages.models.pages.layout.footer_content.default_footer_content,
                        help_text="Structured JSON describing footer sections, links, and CTAs",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one footer can be active at a time",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Content",
                "verbose_name_plural": "Footer Contents",
                "db_table": "pages_footercontent",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "name",
                    models.SlugField(
                        help_text="Machine-readable name (e.g. 'main_nav', 'footer').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated from name if not provided.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this menu's purpose.",
                        null=True,
                    ),
                ),
                (
                    "items",
                    models.JSONField(
                        default=pages.models.pages.layout.menu.default_menu_items,
                        help_text="JSON array of menu items. Each item can be home, page, or external link.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
                "db_table": "pages_menu",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GoogleSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Internal display name used by admins to select this Google Sheet.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "spreadsheet_id",
                    models.CharField(
                        help_text="Google Spreadsheet ID from the sheet URL.",
                        max_length=255,
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        help_text="Worksheet/tab name inside the spreadsheet.",
                        max_length=255,
                    ),
                ),
                (
                    "range_a1",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional A1 range override, for example A1:Z100.",
                        max_length=255,
                    ),
                ),
                (
                    "cache_ttl_seconds",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="How long fetched sheet data should be cached in seconds.",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Disable to block public API access to this saved sheet.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Sheet",
                "verbose_name_plural": "Google Sheets",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["spreadsheet_id", "sheet_name"],
                        name="pages_googl_spreads_b581da_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Pending Publish"),
                            ("published", "Published"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Publishing workflow status.",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the page was first published.",
                        null=True,
                    ),
                ),
                (
                    "submitted_for_review_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when submitted for review.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name to identify this home page version",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one home page can be active at a time",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who published this content.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_for_review_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted for review.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_submitted_review",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
                "verbose_name_plural": "Home Pages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the asset.",
                        unique=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded file.",
                        upload_to=pages.models.media.asset_upload_path,
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        help_text="Original filename as uploaded by user.",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MIME type of the file (e.g., image/png).",
                        max_length=100,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes."
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Alternative text for images (accessibility).",
                        max_length=255,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the file was uploaded."
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded the file.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Asset",
                "verbose_name_plural": "Media Assets",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (will fall back to page title if empty).",
                        max_length=255,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO description for search engines and social sharing.",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated SEO keywords (optional, some search engines may ignore this).",
                        max_length=255,
                    ),
                ),
                (
                    "og_image",
                    models.URLField(
                        blank=True,
                        help_text="Open Graph share image URL (e.g. for social media cards).",
                        null=True,
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Canonical URL for SEO (optional, usually auto-resolved).",
                        null=True,
                    ),
                ),
                (
                    "meta_robots",
                    models.CharField(
                        blank=True,
                        help_text="Robots meta tag value, e.g. 'index,follow' or 'noindex,nofollow'.",
                        max_length=100,
                    ),
                ),
                (
                    "google_site_verification",
                    models.CharField(
                        blank=True,
                        help_text="Google Search Console verification token for this page (optional).",
                        max_length=255,
                    ),
                ),
                (
                    "google_structured_data",
                    models.JSONField(
                        blank=True,
                        help_text="Optional JSON-LD structured data payload for Google Search.",
                        null=True,
                    ),
                ),
                (
                    "slug_depth",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Redundant: number of path segments (e.g. 'about/team' -> 1 slash).",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Redundant: total view count (may be updated externally).",
                    ),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Redundant: timestamp of last page view.",
                        null=True,
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional template name override for rendering this page.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Pending Publish"),
                            ("published", "Published"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Publishing workflow status.",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the page was first published.",
                        null=True,
                    ),
                ),
                (
                    "submitted_for_review_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when submitted for review.",
                        null=True,
                    ),
                ),
                ("page_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Human readable title of the page.", max_length=200
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="User-defined slug. Supports nested paths, e.g. 'about/team'. Do NOT include leading or trailing '/'.",
                        max_length=255,
                        unique=True,
                        validators=[
                            pages.models.pages.shared.validators.validate_nested_slug
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who published this content.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_for_review_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted for review.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_submitted_review",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="MenuPageLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "custom_title",
                    models.CharField(
                        blank=True,
                        help_text="Override the page title for this menu (optional).",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "css_classes",
                    models.CharField(
                        blank=True,
                        help_text="Additional CSS classes for styling.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class name (e.g. 'fa-home' for FontAwesome).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to open the link in a new browser tab.",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        help_text="The menu this link belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.menu",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="The page being linked.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Page Link",
                "verbose_name_plural": "Menu Page Links",
                "db_table": "pages_menupagelink",
                "ordering": ["menu", "order"],
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="pages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Legacy: Pages included in this menu.",
                related_name="menus",
                through="pages.MenuPageLink",
                to="pages.page",
            ),
        ),
        migrations.CreateModel(
            name="PageComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "component_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(default="", max_length=255)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("markdown", "Markdown"),
                            ("form", "Form"),
                            ("table", "Table"),
                            ("google_sheet", "Google Sheet"),
                        ],
                        db_index=True,
                        default="html",
                        max_length=32,
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                ("html_content", models.TextField(blank=True, default="")),
                (
                    "css_file",
                    models.FileField(
                        blank=True, null=True, upload_to="page_components/css/"
                    ),
                ),
                ("css_code", models.TextField(blank=True, default="")),
                ("js_code", models.TextField(blank=True, default="")),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=pages.models.pages.component.page_component.default_config,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="page_components/images/"
                    ),
                ),
                ("image_alt", models.CharField(blank=True, default="", max_length=255)),
                (
                    "image_caption",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("image_link", models.URLField(blank=True, default="")),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="page_components/backgrounds/"
                    ),
                ),
                (
                    "background_image_alt",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "google_sheet_style",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("striped", "Striped"),
                            ("bordered", "Bordered"),
                            ("compact", "Compact"),
                        ],
                        default="default",
                        help_text="Table presentation style for Google Sheet components.",
                        max_length=32,
                    ),
                ),
                (
                    "data_params",
                    models.JSONField(
                        blank=True,
                        default=pages.models.pages.component.page_component.default_config,
                        null=True,
                    ),
                ),
                ("refresh_interval_seconds", models.PositiveIntegerField(default=0)),
                (
                    "hydrate_on_client",
                    models.BooleanField(
                        default=True,
                        help_text="If true, client calls /api/components/<uuid>/data/; otherwise you can embed data server-side.",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="components",
                        to="pages.componentdatasource",
                    ),
                ),
                (
                    "google_sheet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Saved Google Sheet used when component_type is 'google_sheet'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="components",
                        to="pages.googlesheet",
                    ),
                ),
                (
                    "home_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="pages.homepage",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="pages.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Component",
                "verbose_name_plural": "Page Components",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PageComponentAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "asset_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("file", models.FileField(upload_to="page_components/assets/")),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("css", "CSS"),
                            ("js", "JavaScript"),
                            ("pdf", "PDF"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        help_text="Auto-detected from MIME type on upload; can be corrected manually.",
                        max_length=16,
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                ("link", models.URLField(blank=True, default="")),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="pages.pagecomponent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Component Asset",
                "verbose_name_plural": "Page Component Assets",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PageComponentImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "image_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("image", models.ImageField(upload_to="page_components/images/")),
                ("alt", models.CharField(blank=True, default="", max_length=255)),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                ("link", models.URLField(blank=True, default="")),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="pages.pagecomponent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Component Image",
                "verbose_name_plural": "Page Component Images",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UniformForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this form",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable form name (e.g., 'Event Registration')",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for this form",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the form's purpose",
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        default=pages.models.uniforms.form.default_form_fields,
                        help_text="JSON array of form field definitions with types, labels, validation rules, etc.",
                    ),
                ),
                (
                    "submit_button_text",
                    models.CharField(
                        default="Submit",
                        help_text="Text displayed on the submit button",
                        max_length=100,
                    ),
                ),
                (
                    "success_message",
                    models.TextField(
                        default="Thank you for your submission!",
                        help_text="Message displayed after successful submission",
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL to redirect to after submission",
                        null=True,
                    ),
                ),
                (
                    "enable_email_notification",
                    models.BooleanField(
                        default=True,
                        help_text="Send email notification when form is submitted",
                    ),
                ),
                (
                    "notification_recipients",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated email addresses to notify on submission",
                    ),
                ),
                (
                    "email_subject_template",
                    models.CharField(
                        blank=True,
                        help_text="Template for email subject (leave blank for default)",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this form accepts new submissions",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False, help_text="Whether this form is publicly visible"
                    ),
                ),
                (
                    "allow_anonymous",
                    models.BooleanField(
                        default=True,
                        help_text="Allow submissions from users who are not logged in",
                    ),
                ),
                (
                    "login_required",
                    models.BooleanField(
                        default=False,
                        help_text="Require users to be logged in to submit this form",
                    ),
                ),
                (
                    "max_submissions_per_user",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Maximum submissions per user (0 = unlimited)",
                    ),
                ),
                (
                    "submission_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of submissions received"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Form",
                "verbose_name_plural": "Forms",
                "db_table": "pages_uniformform",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="pagecomponent",
            name="form",
            field=models.ForeignKey(
                blank=True,
                help_text="Form to embed when component_type is 'form'.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="page_components",
                to="pages.uniformform",
            ),
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "submission_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this submission",
                        unique=True,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Complete form submission data as key-value pairs"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("processed", "Processed"),
                            ("archived", "Archived"),
                            ("spam", "Marked as Spam"),
                        ],
                        default="pending",
                        help_text="Current processing status of this submission",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this submission"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this submission was reviewed",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the submitter", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Browser user agent string"),
                ),
                (
                    "referrer",
                    models.URLField(
                        blank=True,
                        help_text="Page the user came from",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether email notification has been sent",
                    ),
                ),
                (
                    "notification_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When notification was sent", null=True
                    ),
                ),
                (
                    "notification_error",
                    models.TextField(
                        blank=True, help_text="Error message if notification failed"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this submission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted the form (null for anonymous submissions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        help_text="The form that was submitted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="pages.uniformform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Submission",
                "verbose_name_plural": "Form Submissions",
                "db_table": "pages_formsubmission",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="menupagelink",
            index=models.Index(
                fields=["menu", "order"], name="pages_menu_menu_id_c18fe0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="menupagelink",
            unique_together={("menu", "page")},
        ),
        migrations.AddIndex(
            model_name="pagecomponentasset",
            index=models.Index(
                fields=["component", "order"], name="pages_pagec_compone_adae79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pagecomponentasset",
            index=models.Index(
                fields=["asset_type"], name="pages_pagec_asset_t_e54178_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagecomponentasset",
            constraint=models.UniqueConstraint(
                fields=("component", "order"), name="uniq_component_asset_order"
            ),
        ),
        migrations.AddIndex(
            model_name="pagecomponentimage",
            index=models.Index(
                fields=["component", "order"], name="pages_pagec_compone_c0af52_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagecomponentimage",
            constraint=models.UniqueConstraint(
                fields=("component", "order"), name="uniq_component_image_order"
            ),
        ),
        migrations.AddIndex(
            model_name="uniformform",
            index=models.Index(fields=["slug"], name="pages_form_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="uniformform",
            index=models.Index(
                fields=["is_active", "published"], name="pages_form_active_pub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uniformform",
            index=models.Index(fields=["created_at"], name="pages_form_created_idx"),
        ),
        migrations.AddIndex(
            model_name="pagecomponent",
            index=models.Index(
                fields=["page", "is_enabled", "order"],
                name="pages_pagec_page_id_3dc713_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pagecomponent",
            index=models.Index(
                fields=["home_page", "is_enabled", "order"],
                name="pages_pagec_home_pa_52f8ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pagecomponent",
            index=models.Index(
                fields=["component_type"], name="pages_pagec_compone_7e7770_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pagecomponent",
            index=models.Index(
                fields=["data_source"], name="pages_pagec_data_so_cef6ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pagecomponent",
            index=models.Index(fields=["form"], name="pages_pagec_form_id_308217_idx"),
        ),
        migrations.AddIndex(
            model_name="pagecomponent",
            index=models.Index(
                fields=["google_sheet"], name="pages_pagec_google__1af278_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagecomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("page__isnull", False), ("home_page__isnull", True)),
                    models.Q(("page__isnull", True), ("home_page__isnull", False)),
                    _connector="OR",
                ),
                name="pages_pagecomponent_single_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagecomponent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("page__isnull", False)),
                fields=("page", "order"),
                name="uniq_component_order_per_page",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagecomponent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("home_page__isnull", False)),
                fields=("home_page", "order"),
                name="uniq_component_order_per_homepage",
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["form", "created_at"], name="pages_formsub_form_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(fields=["status"], name="pages_formsub_status_idx"),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["user", "created_at"], name="pages_formsub_user_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(fields=["ip_address"], name="pages_formsub_ip_idx"),
        ),
    ]
