# Generated by Django 4.2.11 on 2025-12-24 11:00

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="page_body",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, help_text="Rich text content for 'page' type.", null=True
            ),
        ),
    ]
