# Generated by Django 4.2.11 on 2025-12-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contactverification",
            new_name="pages_conta_contact_f129c9_idx",
            old_name="pages_conta_contact_05b93e_idx",
        ),
        migrations.RenameIndex(
            model_name="contactverification",
            new_name="pages_conta_is_used_9946cb_idx",
            old_name="pages_conta_is_used_b25c25_idx",
        ),
        migrations.RenameIndex(
            model_name="formsubmission",
            new_name="pages_forms_form_id_d80c17_idx",
            old_name="pages_forms_form_id__8a4777_idx",
        ),
        migrations.RenameIndex(
            model_name="formsubmission",
            new_name="pages_forms_is_veri_05a46d_idx",
            old_name="pages_forms_is_veri_5132bb_idx",
        ),
        migrations.RenameIndex(
            model_name="formsubmission",
            new_name="pages_forms_contact_679b13_idx",
            old_name="pages_forms_contact_c979b3_idx",
        ),
        migrations.RenameIndex(
            model_name="formsubmission",
            new_name="pages_forms_contact_adb415_idx",
            old_name="pages_forms_contact_3e7ca0_idx",
        ),
        migrations.AddField(
            model_name="page",
            name="google_site_verification",
            field=models.CharField(
                blank=True,
                help_text="Google Search Console verification token for this page (optional).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="google_structured_data",
            field=models.JSONField(
                blank=True,
                help_text="Optional JSON-LD structured data payload for Google Search.",
                null=True,
            ),
        ),
    ]
