# Generated by Django 5.2.10 on 2026-03-28 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsFeedSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("name", models.CharField(max_length=200)),
                ("feed_url", models.URLField(max_length=1000)),
                (
                    "source_key",
                    models.SlugField(default="ucmerced", max_length=100, unique=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_created", models.PositiveIntegerField(default=0)),
                ("last_sync_updated", models.PositiveIntegerField(default=0)),
                ("last_sync_errors", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "source",
                    models.CharField(db_index=True, default="ucmerced", max_length=100),
                ),
                ("source_guid", models.CharField(max_length=500, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("source_url", models.URLField(max_length=1000)),
                ("summary", models.TextField(blank=True, default="")),
                ("image_url", models.URLField(blank=True, default="", max_length=1000)),
                ("author", models.CharField(blank=True, default="", max_length=255)),
                ("content", models.TextField(blank=True, default="")),
                (
                    "hero_image_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                (
                    "hero_caption",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("published_at", models.DateTimeField(db_index=True)),
                ("raw_payload", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "source_guid"],
                        name="pages_newsa_source_25732b_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NewsSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("duration_seconds", models.FloatField(default=0)),
                ("articles_created", models.PositiveIntegerField(default=0)),
                ("articles_updated", models.PositiveIntegerField(default=0)),
                ("errors_text", models.TextField(blank=True, default="")),
                (
                    "feed_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="pages.newsfeedsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["feed_source", "-started_at"],
                        name="pages_synclog_source_started",
                    )
                ],
            },
        ),
    ]
