# Generated by Django 5.2.10 on 2026-02-20

"""
Step 1: Create PageComponentPlacement table and M2M fields.
Old page/home_page/order fields on PageComponent are kept temporarily
for the data migration in 0003.
"""

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        # Create the new through table
        migrations.CreateModel(
            name="PageComponentPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="pages.pagecomponent",
                    ),
                ),
                (
                    "home_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_placements",
                        to="pages.homepage",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_placements",
                        to="pages.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component Placement",
                "verbose_name_plural": "Component Placements",
                "ordering": ["order", "id"],
            },
        ),
        # Add M2M fields on Page and HomePage
        migrations.AddField(
            model_name="homepage",
            name="components",
            field=models.ManyToManyField(
                blank=True,
                through="pages.PageComponentPlacement",
                to="pages.pagecomponent",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="components",
            field=models.ManyToManyField(
                blank=True,
                through="pages.PageComponentPlacement",
                to="pages.pagecomponent",
            ),
        ),
        # Add indexes on placement table
        migrations.AddIndex(
            model_name="pagecomponentplacement",
            index=models.Index(
                fields=["page", "order"], name="pages_pagec_page_id_7c84ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pagecomponentplacement",
            index=models.Index(
                fields=["home_page", "order"], name="pages_pagec_home_pa_6d17b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pagecomponentplacement",
            index=models.Index(
                fields=["component"], name="pages_pagec_compone_c5626f_idx"
            ),
        ),
        # Add constraints on placement table
        migrations.AddConstraint(
            model_name="pagecomponentplacement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("page__isnull", False)),
                fields=("page", "order"),
                name="uniq_placement_order_per_page",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagecomponentplacement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("home_page__isnull", False)),
                fields=("home_page", "order"),
                name="uniq_placement_order_per_homepage",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagecomponentplacement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("page__isnull", False)),
                fields=("component", "page"),
                name="uniq_component_per_page",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagecomponentplacement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("home_page__isnull", False)),
                fields=("component", "home_page"),
                name="uniq_component_per_homepage",
            ),
        ),
    ]
