# Generated by Django 4.2.11 on 2026-01-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecomponent",
            name="js_code",
            field=models.TextField(
                blank=True,
                default="",
                help_text="JavaScript code to execute within this component (runs in isolated scope).",
            ),
        ),
    ]
