# Generated by Django 4.2.11 on 2025-12-22 08:03

from django.db import migrations, models
import layout.models.footer_content


class Migration(migrations.Migration):

    dependencies = [
        (
            "pages",
            "0002_rename_pages_conta_contact_05b93e_idx_pages_conta_contact_f129c9_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name to identify this footer version",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Machine-readable key for this footer version",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        default=layout.models.footer_content.default_footer_content,
                        help_text="Structured JSON describing footer sections, links, and CTAs",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one footer can be active at a time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Footer Content",
                "verbose_name_plural": "Footer Contents",
                "ordering": ["-created_at"],
            },
        ),
    ]
