# Generated by Django 4.2.11 on 2025-12-29 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pages.models.pages.page_component
import pages.models.uniforms.forms
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0002_alter_page_page_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="body",
        ),
        migrations.RemoveField(
            model_name="page",
            name="external_url",
        ),
        migrations.RemoveField(
            model_name="page",
            name="page_body",
        ),
        migrations.RemoveField(
            model_name="page",
            name="page_type",
        ),
        migrations.CreateModel(
            name="UniformForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this form",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable form name (e.g., 'Event Registration')",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for this form",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the form's purpose",
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        default=pages.models.uniforms.forms.default_form_fields,
                        help_text="JSON array of form field definitions with types, labels, validation rules, etc.",
                    ),
                ),
                (
                    "submit_button_text",
                    models.CharField(
                        default="Submit",
                        help_text="Text displayed on the submit button",
                        max_length=100,
                    ),
                ),
                (
                    "success_message",
                    models.TextField(
                        default="Thank you for your submission!",
                        help_text="Message displayed after successful submission",
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL to redirect to after submission",
                        null=True,
                    ),
                ),
                (
                    "enable_email_notification",
                    models.BooleanField(
                        default=True,
                        help_text="Send email notification when form is submitted",
                    ),
                ),
                (
                    "notification_recipients",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated email addresses to notify on submission",
                    ),
                ),
                (
                    "email_subject_template",
                    models.CharField(
                        blank=True,
                        help_text="Template for email subject (leave blank for default)",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this form accepts new submissions",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False, help_text="Whether this form is publicly visible"
                    ),
                ),
                (
                    "allow_anonymous",
                    models.BooleanField(
                        default=True,
                        help_text="Allow submissions from users who are not logged in",
                    ),
                ),
                (
                    "login_required",
                    models.BooleanField(
                        default=False,
                        help_text="Require users to be logged in to submit this form",
                    ),
                ),
                (
                    "max_submissions_per_user",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Maximum submissions per user (0 = unlimited)",
                    ),
                ),
                (
                    "submission_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of submissions received"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Form",
                "verbose_name_plural": "Forms",
                "db_table": "pages_uniformform",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="pages_form_slug_idx"),
                    models.Index(
                        fields=["is_active", "published"],
                        name="pages_form_active_pub_idx",
                    ),
                    models.Index(fields=["created_at"], name="pages_form_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PageComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("form", "Form"),
                            ("google_sheet", "Google Sheet"),
                            ("sheet", "Sheet"),
                        ],
                        default="html",
                        help_text="Type of component to render.",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers render first).",
                    ),
                ),
                (
                    "html_content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="HTML content when component_type='html'.",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=pages.models.pages.page_component.default_config,
                        help_text="Structured config for non-HTML component types.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "home_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent HomePage (set for homepage versions).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="pages.homepage",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent Page (set for standard pages).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="pages.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Component",
                "verbose_name_plural": "Page Components",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this submission",
                        unique=True,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Complete form submission data as key-value pairs"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("processed", "Processed"),
                            ("archived", "Archived"),
                            ("spam", "Marked as Spam"),
                        ],
                        default="pending",
                        help_text="Current processing status of this submission",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this submission"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this submission was reviewed",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the submitter", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Browser user agent string"),
                ),
                (
                    "referrer",
                    models.URLField(
                        blank=True,
                        help_text="Page the user came from",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether email notification has been sent",
                    ),
                ),
                (
                    "notification_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When notification was sent", null=True
                    ),
                ),
                (
                    "notification_error",
                    models.TextField(
                        blank=True, help_text="Error message if notification failed"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this form was submitted"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this submission was last updated"
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        help_text="The form that was submitted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="pages.uniformform",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this submission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted the form (null for anonymous submissions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Submission",
                "verbose_name_plural": "Form Submissions",
                "db_table": "pages_formsubmission",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="pagecomponent",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("page__isnull", False), ("home_page__isnull", True)),
                    models.Q(("page__isnull", True), ("home_page__isnull", False)),
                    _connector="OR",
                ),
                name="pages_pagecomponent_single_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["form", "submitted_at"], name="pages_formsub_form_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(fields=["status"], name="pages_formsub_status_idx"),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["user", "submitted_at"], name="pages_formsub_user_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(fields=["ip_address"], name="pages_formsub_ip_idx"),
        ),
    ]
