# Generated by Django 5.2.10 on 2026-02-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_add_grapesjs_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uniformform",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="uniformform",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="FormSubmission",
        ),
        migrations.DeleteModel(
            name="UniformForm",
        ),
    ]
