# Generated by Django 5.2.10 on 2026-02-18 03:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_merge_layout_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "Pending Publish"),
                    ("published", "Published"),
                ],
                db_index=True,
                default="draft",
                help_text="Publishing workflow status.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "Pending Publish"),
                    ("published", "Published"),
                ],
                db_index=True,
                default="draft",
                help_text="Publishing workflow status.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PageComponentAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "asset_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("file", models.FileField(upload_to="page_components/assets/")),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("css", "CSS"),
                            ("js", "JavaScript"),
                            ("pdf", "PDF"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        help_text="Auto-detected from MIME type on upload; can be corrected manually.",
                        max_length=16,
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                ("link", models.URLField(blank=True, default="")),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="pages.pagecomponent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Component Asset",
                "verbose_name_plural": "Page Component Assets",
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(
                        fields=["component", "order"],
                        name="pages_pagec_compone_adae79_idx",
                    ),
                    models.Index(
                        fields=["asset_type"], name="pages_pagec_asset_t_e54178_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("component", "order"), name="uniq_component_asset_order"
                    )
                ],
            },
        ),
    ]
