# Generated by Django 4.2.11 on 2025-12-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_remove_homepage_body_remove_page_external_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecomponent",
            name="css_code",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Inline CSS applied to this component (scoped by renderer).",
            ),
        ),
        migrations.AddField(
            model_name="pagecomponent",
            name="css_file",
            field=models.FileField(
                blank=True,
                help_text="Optional CSS file to load for this component.",
                null=True,
                upload_to="page_components/css/",
            ),
        ),
    ]
