# Generated by Django 5.1.15 on 2026-02-25 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pages", "0003_remove_form_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="scheduled_publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Scheduled date/time for automatic publishing.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="scheduled_publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Scheduled date/time for automatic publishing.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "Pending Publish"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                ],
                db_index=True,
                default="draft",
                help_text="Publishing workflow status.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "Pending Publish"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                ],
                db_index=True,
                default="draft",
                help_text="Publishing workflow status.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PagePreviewToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("object_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this preview link expires."),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional note about this preview link.",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preview_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Preview Token",
                "verbose_name_plural": "Page Preview Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-defined component name.", max_length=200
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="Custom",
                        help_text="Component category for grouping.",
                        max_length=100,
                    ),
                ),
                (
                    "grapesjs_data",
                    models.JSONField(
                        default=dict, help_text="GrapesJS component JSON data."
                    ),
                ),
                (
                    "html",
                    models.TextField(
                        blank=True, default="", help_text="Rendered HTML for preview."
                    ),
                ),
                (
                    "css",
                    models.TextField(
                        blank=True, default="", help_text="Associated CSS styles."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_shared",
                    models.BooleanField(
                        default=True,
                        help_text="Visible to all editors or just the creator.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_components",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Component",
                "verbose_name_plural": "Saved Components",
                "ordering": ["-created_at"],
            },
        ),
    ]
