# Generated by Django 4.2.11 on 2025-12-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_remove_layout_models"),
    ]

    operations = [
        # First, remove the form foreign key from Page model
        migrations.RemoveField(
            model_name="page",
            name="form",
        ),
        # Update page_type choices
        migrations.AlterField(
            model_name="page",
            name="page_type",
            field=models.CharField(
                choices=[("page", "Rich Text Page"), ("external", "External URL")],
                default="page",
                help_text="Page behavior type.",
                max_length=20,
            ),
        ),
        # Remove indexes from FormSubmission before deleting
        migrations.RemoveIndex(
            model_name="formsubmission",
            name="pages_forms_form_id_d80c17_idx",
        ),
        migrations.RemoveIndex(
            model_name="formsubmission",
            name="pages_forms_is_veri_05a46d_idx",
        ),
        migrations.RemoveIndex(
            model_name="formsubmission",
            name="pages_forms_contact_679b13_idx",
        ),
        migrations.RemoveIndex(
            model_name="formsubmission",
            name="pages_forms_contact_adb415_idx",
        ),
        # Remove indexes from ContactVerification
        migrations.RemoveIndex(
            model_name="contactverification",
            name="pages_conta_contact_f129c9_idx",
        ),
        migrations.RemoveIndex(
            model_name="contactverification",
            name="pages_conta_is_used_9946cb_idx",
        ),
        # Remove unique_together constraint from FormField
        migrations.AlterUniqueTogether(
            name="formfield",
            unique_together=set(),
        ),
        # Now delete the models in the correct order (dependencies first)
        migrations.DeleteModel(
            name="FormSubmission",
        ),
        migrations.DeleteModel(
            name="FormField",
        ),
        migrations.DeleteModel(
            name="ContactVerification",
        ),
        migrations.DeleteModel(
            name="Form",
        ),
    ]
