# Generated by Django 5.2.10 on 2026-02-18 03:07

from django.db import migrations


def migrate_images_to_assets(apps, schema_editor):
    """Copy existing PageComponentImage rows into PageComponentAsset (type=image)."""
    PageComponentImage = apps.get_model("pages", "PageComponentImage")
    PageComponentAsset = apps.get_model("pages", "PageComponentAsset")

    assets_to_create = []
    for img in PageComponentImage.objects.all():
        assets_to_create.append(
            PageComponentAsset(
                component=img.component,
                file=img.image.name if img.image else "",
                asset_type="image",
                order=img.order,
                title=img.alt,
                caption=img.caption,
                link=img.link,
            )
        )

    if assets_to_create:
        PageComponentAsset.objects.bulk_create(assets_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_add_pagecomponentasset"),
    ]

    operations = [
        migrations.RunPython(migrate_images_to_assets, migrations.RunPython.noop),
    ]
