# Generated by Django 4.2.27 on 2026-01-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_pagecomponent_css_code_pagecomponent_css_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "home_page_mode",
                    models.CharField(
                        choices=[
                            ("pre_event", "Pre Event"),
                            ("during_semester", "During Semester"),
                            ("event", "Event"),
                        ],
                        default="pre_event",
                        help_text="Select which home page variant to display",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
                "ordering": ["-updated_at"],
            },
        ),
    ]
