# Generated by Django 4.2.27 on 2026-01-07 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_sitesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedProjectURL",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the shared URL.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "team_names",
                    models.JSONField(
                        default=list, help_text="List of team names to filter projects."
                    ),
                ),
                (
                    "team_numbers",
                    models.JSONField(
                        default=list,
                        help_text="List of team numbers to filter projects.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this shared URL was created."
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiration date for the shared URL.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Project URL",
                "verbose_name_plural": "Shared Project URLs",
                "ordering": ["-created_at"],
            },
        ),
    ]
