# Generated by Django 5.2.10 on 2026-02-18 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_migrate_images_to_assets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the page was first published.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published this content.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_published",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="submitted_for_review_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted for review.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_submitted_review",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pagecomponent",
            name="component_type",
            field=models.CharField(
                choices=[
                    ("html", "HTML"),
                    ("markdown", "Markdown"),
                    ("form", "Form"),
                    ("table", "Table"),
                ],
                db_index=True,
                default="html",
                max_length=32,
            ),
        ),
    ]
