# Generated by Django 5.2.10 on 2026-03-04 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_add_missing_grapesjs_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Only one home page can be active at a time",
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["slug", "status"], name="page_slug_status_idx"),
        ),
    ]
