# Generated by Django 5.2.10 on 2026-02-18 08:56

from django.db import migrations


def convert_old_types(apps, schema_editor):
    PageComponent = apps.get_model("pages", "PageComponent")
    PageComponent.objects.filter(component_type__in=["template", "widget"]).update(component_type="html")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_homepage_created_by_homepage_updated_by_and_more"),
    ]

    operations = [
        migrations.RunPython(convert_old_types, noop),
    ]
