# Generated by Django 4.2.27 on 2026-01-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_sharedprojecturl"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedprojecturl",
            name="project_keys",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of unique project keys (JSON strings) for precise matching.",
            ),
        ),
    ]
