# Generated by Django 4.2.11 on 2025-12-22 10:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_change_homepage_body_to_textfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=tinymce.models.HTMLField(blank=True, help_text="Rich text content"),
        ),
    ]
