# Generated by Django 5.2.10 on 2026-03-05 21:03

import pages.models.pages.layout.menu
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_alter_homepage_is_active_page_page_slug_status_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="items",
            field=models.JSONField(
                default=pages.models.pages.layout.menu.default_menu_items,
                help_text="JSON array of menu items. Each item can be home, page, external link, or app route.",
            ),
        ),
    ]
