# Generated by Django 5.2.10 on 2026-03-09 05:38

import pages.models.pages.layout.menu
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_alter_menu_items"),
    ]

    operations = [
        # 1. Remove M2M field from Menu first (references MenuPageLink through model)
        migrations.RemoveField(
            model_name="menu",
            name="pages",
        ),
        # 2. Update Menu.items field default/help_text
        migrations.AlterField(
            model_name="menu",
            name="items",
            field=models.JSONField(
                default=pages.models.pages.layout.menu.default_menu_items,
                help_text="JSON array of menu items. Each item can be an external link or app route.",
            ),
        ),
        # 3. Delete models (order: dependents first, then referenced models)
        migrations.DeleteModel(
            name="GoogleSheet",
        ),
        migrations.DeleteModel(
            name="MenuPageLink",
        ),
        migrations.DeleteModel(
            name="PagePreviewToken",
        ),
        migrations.DeleteModel(
            name="SavedComponent",
        ),
        migrations.DeleteModel(
            name="MediaAsset",
        ),
        migrations.DeleteModel(
            name="HomePage",
        ),
        migrations.DeleteModel(
            name="Page",
        ),
    ]
