# Generated by Django 5.2.10 on 2026-02-19 04:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_convert_component_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecomponent",
            name="google_sheet_style",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("striped", "Striped"),
                    ("bordered", "Bordered"),
                    ("compact", "Compact"),
                ],
                default="default",
                help_text="Table presentation style for Google Sheet components.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="pagecomponent",
            name="component_type",
            field=models.CharField(
                choices=[
                    ("html", "HTML"),
                    ("markdown", "Markdown"),
                    ("form", "Form"),
                    ("table", "Table"),
                    ("google_sheet", "Google Sheet"),
                ],
                db_index=True,
                default="html",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="GoogleSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Internal display name used by admins to select this Google Sheet.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "spreadsheet_id",
                    models.CharField(
                        help_text="Google Spreadsheet ID from the sheet URL.",
                        max_length=255,
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        help_text="Worksheet/tab name inside the spreadsheet.",
                        max_length=255,
                    ),
                ),
                (
                    "range_a1",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional A1 range override, for example A1:Z100.",
                        max_length=255,
                    ),
                ),
                (
                    "cache_ttl_seconds",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="How long fetched sheet data should be cached in seconds.",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Disable to block public API access to this saved sheet.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Sheet",
                "verbose_name_plural": "Google Sheets",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["spreadsheet_id", "sheet_name"],
                        name="pages_googl_spreads_b581da_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="pagecomponent",
            name="google_sheet",
            field=models.ForeignKey(
                blank=True,
                help_text="Saved Google Sheet used when component_type is 'google_sheet'.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components",
                to="pages.googlesheet",
            ),
        ),
        migrations.AddIndex(
            model_name="pagecomponent",
            index=models.Index(
                fields=["google_sheet"], name="pages_pagec_google__1af278_idx"
            ),
        ),
    ]
