# Generated by Django 4.2.11 on 2025-12-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_use_tinymce_htmlfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=models.TextField(blank=True, help_text="Rich text content (HTML)"),
        ),
    ]
