# Generated by Django 5.2.10 on 2026-03-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_delete_googlesheet_remove_mediaasset_uploaded_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "homepage_mode",
                    models.CharField(
                        choices=[
                            ("pre-event", "Pre-Event"),
                            ("during-semester", "During Semester"),
                            ("during-event", "During Event"),
                            ("post-event", "Post-Event"),
                        ],
                        default="post-event",
                        help_text="Controls which homepage variant is displayed.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
