# Generated by Django 5.2.10 on 2026-03-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_sitesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleSheetSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="API lookup key, e.g. 'current-event', '2025-fall'",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="Display name", max_length=200)),
                (
                    "sheet_type",
                    models.CharField(
                        choices=[
                            ("current-event", "Current Event"),
                            ("past-projects", "Past Projects"),
                            ("archive-event", "Archive Event"),
                        ],
                        help_text="Controls parsing logic",
                        max_length=20,
                    ),
                ),
                (
                    "spreadsheet_id",
                    models.CharField(
                        help_text="Google Sheets spreadsheet ID", max_length=200
                    ),
                ),
                (
                    "range_a1",
                    models.CharField(
                        help_text="Sheet range, e.g. 'A1:Y76' or 'Past-Projects-WEB-LIVE'",
                        max_length=200,
                    ),
                ),
                (
                    "tracks_spreadsheet_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional separate spreadsheet for track info",
                        max_length=200,
                    ),
                ),
                (
                    "tracks_sheet_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Track info sheet name, e.g. '2025-I2G2-Tracks'",
                        max_length=200,
                    ),
                ),
                (
                    "semester_filter",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional row filter, e.g. '2025-2 Fall'",
                        max_length=100,
                    ),
                ),
                (
                    "cache_ttl_seconds",
                    models.PositiveIntegerField(
                        default=300, help_text="Cache TTL in seconds"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Disable without deleting"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sheet Source",
                "verbose_name_plural": "Sheet Sources",
                "ordering": ["slug"],
            },
        ),
    ]
