# Generated by Django 5.2.10 on 2026-03-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_googlesheetsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="homepage_route",
            field=models.CharField(
                blank=True,
                default="/",
                help_text='Route path to render as the homepage (e.g. "/event", "/about"). Use "/" for the default homepage.',
                max_length=100,
            ),
        ),
    ]
