# Generated by Django 5.2.10 on 2026-03-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_sitesettings_homepage_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Only active menus are served to the frontend."
            ),
        ),
    ]
