# Generated by Django 5.2.10 on 2026-01-30 03:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "event_name",
                    models.CharField(help_text="Name of the event.", max_length=255),
                ),
                (
                    "event_date_time",
                    models.DateTimeField(help_text="Date of the event."),
                ),
                (
                    "upper_bullet_points",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Upper bullet points in Markdown format (array of strings).",
                    ),
                ),
                (
                    "lower_bullet_points",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lower bullet points in Markdown format (array of strings).",
                    ),
                ),
                (
                    "expo_table",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Expo table rows: [{time, room, description}]",
                    ),
                ),
                (
                    "reception_table",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Reception table rows: [{time, room, description}]",
                    ),
                ),
                (
                    "special_awards",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Special awards as array of strings (e.g., ['Award 1', 'Award 2']).",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this event is published and visible.",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique slug identifier for the event (e.g., 'spring-expo-2026').",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_live",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this event is currently live (only one event can be live at a time).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-event_date_time", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_name",
                    models.CharField(help_text="Name of the program.", max_length=255),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order for programs.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event this program belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "ordering": ["order", "id"],
                "unique_together": {("event", "program_name")},
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "track_name",
                    models.CharField(help_text="Name of the track.", max_length=255),
                ),
                (
                    "room",
                    models.CharField(
                        help_text="Room assignment for this track.", max_length=255
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Start time for presentations in this track.",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order for tracks within the program.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="The program this track belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="events.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Track",
                "verbose_name_plural": "Tracks",
                "ordering": ["order", "id"],
                "unique_together": {("program", "track_name")},
            },
        ),
        migrations.CreateModel(
            name="SpecialAward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "program_name",
                    models.CharField(help_text="Name of the program.", max_length=255),
                ),
                (
                    "award_winner",
                    models.CharField(
                        help_text="Name of the award winner.", max_length=255
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event this award belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_award_winners",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Special Award",
                "verbose_name_plural": "Special Awards",
                "unique_together": {("event", "program_name")},
            },
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Presentation order within the track (must be > 0).",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "team_id",
                    models.CharField(
                        blank=True,
                        help_text="Team identifier.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the team.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "project_title",
                    models.CharField(help_text="Title of the project.", max_length=500),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization name.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        blank=True, help_text="Abstract/project description.", null=True
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        help_text="The track this presentation belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentations",
                        to="events.track",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presentation",
                "verbose_name_plural": "Presentations",
                "ordering": ["order", "id"],
                "unique_together": {("track", "order")},
            },
        ),
        migrations.CreateModel(
            name="TrackWinner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "track_name",
                    models.CharField(
                        help_text="Name of the track (matches Track.track_name).",
                        max_length=255,
                    ),
                ),
                (
                    "winner_name",
                    models.CharField(
                        help_text="Name of the winning team/presentation.",
                        max_length=255,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event this winner belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_winners",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Track Winner",
                "verbose_name_plural": "Track Winners",
                "unique_together": {("event", "track_name")},
            },
        ),
    ]
