# Generated by Django 4.2.11 on 2026-01-10 09:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "event_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the event.",
                        unique=True,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(help_text="Name of the event.", max_length=255),
                ),
                ("event_date", models.DateField(help_text="Date of the event.")),
                ("event_time", models.TimeField(help_text="Time of the event.")),
                (
                    "upper_bullet_points",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Upper bullet points in Markdown format (array of strings).",
                    ),
                ),
                (
                    "lower_bullet_points",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lower bullet points in Markdown format (array of strings).",
                    ),
                ),
                (
                    "expo_table",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Expo table rows: [{time, room, description}]",
                    ),
                ),
                (
                    "reception_table",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Reception table rows: [{time, room, description}]",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this event is published and visible.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-event_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "program_name",
                    models.CharField(help_text="Name of the program.", max_length=255),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event this program belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "ordering": ["order", "id"],
                "unique_together": {("event", "program_name")},
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "track_name",
                    models.CharField(help_text="Name of the track.", max_length=255),
                ),
                (
                    "room",
                    models.CharField(
                        help_text="Room assignment for this track.", max_length=255
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Start time for presentations in this track.",
                        null=True,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="The program this track belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="events.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Track",
                "verbose_name_plural": "Tracks",
                "ordering": ["order", "id"],
                "unique_together": {("program", "track_name")},
            },
        ),
        migrations.CreateModel(
            name="TrackWinner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "track_name",
                    models.CharField(
                        help_text="Name of the track (matches Track.track_name).",
                        max_length=255,
                    ),
                ),
                (
                    "winner_name",
                    models.CharField(
                        help_text="Name of the winning team/presentation.",
                        max_length=255,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event this winner belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_winners",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Track Winner",
                "verbose_name_plural": "Track Winners",
                "unique_together": {("event", "track_name")},
            },
        ),
        migrations.CreateModel(
            name="SpecialAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_name",
                    models.CharField(
                        help_text="Name of the program (matches Program.program_name).",
                        max_length=255,
                    ),
                ),
                (
                    "award_winner",
                    models.CharField(
                        help_text="Name of the award winner.", max_length=255
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event this award belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_awards",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Special Award",
                "verbose_name_plural": "Special Awards",
                "unique_together": {("event", "program_name")},
            },
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Presentation order within the track (must be > 0).",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "team_id",
                    models.CharField(
                        blank=True,
                        help_text="Team identifier.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the team.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "project_title",
                    models.CharField(help_text="Title of the project.", max_length=500),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization name.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        help_text="The track this presentation belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentations",
                        to="events.track",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presentation",
                "verbose_name_plural": "Presentations",
                "ordering": ["order", "id"],
                "unique_together": {("track", "order")},
            },
        ),
    ]
