# Generated by Django 5.2.10 on 2026-02-19 07:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "event_name",
                    models.CharField(help_text="Name of the event.", max_length=255),
                ),
                (
                    "event_date_time",
                    models.DateTimeField(help_text="Date of the event."),
                ),
                (
                    "upper_bullet_points",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Upper bullet points in Markdown format (array of strings).",
                    ),
                ),
                (
                    "lower_bullet_points",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lower bullet points in Markdown format (array of strings).",
                    ),
                ),
                (
                    "expo_table",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Expo table rows: [{time, room, description}]",
                    ),
                ),
                (
                    "reception_table",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Reception table rows: [{time, room, description}]",
                    ),
                ),
                (
                    "special_awards",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Special awards as array of strings (e.g., ['Award 1', 'Award 2']).",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this event is published and visible.",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique slug identifier for the event (e.g., 'spring-expo-2026').",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_live",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this event is currently live (only one event can be live at a time).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-event_date_time", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("prompt", models.CharField(max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                ("required", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("otp_pending", "OTP Pending"),
                            ("verified", "Verified"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "ticket_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "source_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("primary_email_subscribed", models.BooleanField(default=False)),
                ("secondary_email_subscribed", models.BooleanField(default=False)),
                ("phone_subscribed", models.BooleanField(default=False)),
                ("phone_verified", models.BooleanField(default=False)),
                (
                    "registration_token",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "otp_target_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("otp_requested_at", models.DateTimeField(blank=True, null=True)),
                ("otp_verified_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("profile_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the member registered for this event",
                        verbose_name="Registered At",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event this registration is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="The member who registered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistrationAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("question_prompt", models.CharField(max_length=500)),
                ("answer_text", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answers",
                        to="events.eventquestion",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="events.eventregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="EventTicketOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("label", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_options",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="ticket_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registrations",
                to="events.eventticketoption",
            ),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_name",
                    models.CharField(help_text="Name of the program.", max_length=255),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order for programs.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event this program belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SpecialAward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "program_name",
                    models.CharField(help_text="Name of the program.", max_length=255),
                ),
                (
                    "award_winner",
                    models.CharField(
                        help_text="Name of the award winner.", max_length=255
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event this award belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_award_winners",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Special Award",
                "verbose_name_plural": "Special Awards",
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "track_name",
                    models.CharField(help_text="Name of the track.", max_length=255),
                ),
                (
                    "room",
                    models.CharField(
                        help_text="Room assignment for this track.", max_length=255
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Start time for presentations in this track.",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order for tracks within the program.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="The program this track belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="events.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Track",
                "verbose_name_plural": "Tracks",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Presentation order within the track (must be > 0).",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "team_id",
                    models.CharField(
                        blank=True,
                        help_text="Team identifier.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the team.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "project_title",
                    models.CharField(help_text="Title of the project.", max_length=500),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization name.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        blank=True, help_text="Abstract/project description.", null=True
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        help_text="The track this presentation belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentations",
                        to="events.track",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presentation",
                "verbose_name_plural": "Presentations",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrackWinner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "track_name",
                    models.CharField(
                        help_text="Name of the track (matches Track.track_name).",
                        max_length=255,
                    ),
                ),
                (
                    "winner_name",
                    models.CharField(
                        help_text="Name of the winning team/presentation.",
                        max_length=255,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event this winner belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_winners",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Track Winner",
                "verbose_name_plural": "Track Winners",
            },
        ),
        migrations.AddIndex(
            model_name="eventquestion",
            index=models.Index(
                fields=["event", "order"], name="events_even_event_i_e1932f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventquestion",
            index=models.Index(
                fields=["is_active"], name="events_even_is_acti_8887cd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventquestion",
            unique_together={("event", "prompt")},
        ),
        migrations.AddIndex(
            model_name="eventregistrationanswer",
            index=models.Index(
                fields=["registration", "order"], name="events_even_registr_03a2ab_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventregistrationanswer",
            unique_together={("registration", "question_prompt")},
        ),
        migrations.AddIndex(
            model_name="eventticketoption",
            index=models.Index(
                fields=["event", "order"], name="events_even_event_i_c8058d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventticketoption",
            index=models.Index(
                fields=["is_active"], name="events_even_is_acti_ad6f79_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventticketoption",
            unique_together={("event", "label")},
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(fields=["event"], name="events_even_event_i_9a7faf_idx"),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["member"], name="events_even_member__8c71cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["registered_at"], name="events_even_registe_659dc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(fields=["status"], name="events_even_status_bdf692_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together={("event", "member")},
        ),
        migrations.AlterUniqueTogether(
            name="program",
            unique_together={("event", "program_name")},
        ),
        migrations.AlterUniqueTogether(
            name="specialaward",
            unique_together={("event", "program_name")},
        ),
        migrations.AlterUniqueTogether(
            name="track",
            unique_together={("program", "track_name")},
        ),
        migrations.AlterUniqueTogether(
            name="presentation",
            unique_together={("track", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="trackwinner",
            unique_together={("event", "track_name")},
        ),
    ]
