# Generated by Django 5.2.10 on 2026-02-11 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("prompt", models.CharField(max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                ("required", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("otp_pending", "OTP Pending"),
                            ("verified", "Verified"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "ticket_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "source_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("primary_email_subscribed", models.BooleanField(default=False)),
                ("secondary_email_subscribed", models.BooleanField(default=False)),
                ("phone_subscribed", models.BooleanField(default=False)),
                ("phone_verified", models.BooleanField(default=False)),
                (
                    "registration_token",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "otp_target_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("otp_requested_at", models.DateTimeField(blank=True, null=True)),
                ("otp_verified_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("profile_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the member registered for this event",
                        verbose_name="Registered At",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event this registration is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="The member who registered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistrationAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("question_prompt", models.CharField(max_length=500)),
                ("answer_text", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answers",
                        to="events.eventquestion",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="events.eventregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="EventTicketOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("label", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_options",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="ticket_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registrations",
                to="events.eventticketoption",
            ),
        ),
        migrations.AddIndex(
            model_name="eventquestion",
            index=models.Index(
                fields=["event", "order"], name="events_even_event_i_e1932f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventquestion",
            index=models.Index(
                fields=["is_active"], name="events_even_is_acti_8887cd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventquestion",
            unique_together={("event", "prompt")},
        ),
        migrations.AddIndex(
            model_name="eventregistrationanswer",
            index=models.Index(
                fields=["registration", "order"], name="events_even_registr_03a2ab_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventregistrationanswer",
            unique_together={("registration", "question_prompt")},
        ),
        migrations.AddIndex(
            model_name="eventticketoption",
            index=models.Index(
                fields=["event", "order"], name="events_even_event_i_c8058d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventticketoption",
            index=models.Index(
                fields=["is_active"], name="events_even_is_acti_ad6f79_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventticketoption",
            unique_together={("event", "label")},
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(fields=["event"], name="events_even_event_i_9a7faf_idx"),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["member"], name="events_even_member__8c71cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["registered_at"], name="events_even_registe_659dc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(fields=["status"], name="events_even_status_bdf692_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together={("event", "member")},
        ),
    ]
