# Generated by Django 4.2.27 on 2025-12-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentation",
            name="organization",
            field=models.CharField(
                blank=True, help_text="Organization name.", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="team_id",
            field=models.CharField(
                blank=True, help_text="Team identifier.", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="team_name",
            field=models.CharField(
                blank=True, help_text="Name of the team.", max_length=255, null=True
            ),
        ),
    ]
