# Generated by Django 5.2.10 on 2026-03-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="is_published",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this event is published and visible.",
            ),
        ),
    ]
