# Generated by Django 4.2.27 on 2026-01-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_presentation_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="expo_table",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Expo table rows: [{time, room, description}]",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="reception_table",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Reception table rows: [{time, room, description}]",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="start_time",
            field=models.TimeField(
                blank=True,
                help_text="Start time for presentations in this track.",
                null=True,
            ),
        ),
    ]
