# Generated by Django 4.2.27 on 2026-01-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_add_slug_and_status_to_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="special_awards",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Special awards as array of strings (e.g., ['Award 1', 'Award 2']).",
            ),
        ),
        migrations.DeleteModel(
            name="SpecialAward",
        ),
    ]
