# Generated by Django 4.2.27 on 2026-01-12 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0005_event_special_awards_delete_specialaward"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the member registered for this event",
                        verbose_name="Registered At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this registration was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event this registration is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="The member who registered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
                "ordering": ["-registered_at"],
                "indexes": [
                    models.Index(
                        fields=["event"], name="events_even_event_i_9a7faf_idx"
                    ),
                    models.Index(
                        fields=["member"], name="events_even_member__8c71cb_idx"
                    ),
                    models.Index(
                        fields=["registered_at"], name="events_even_registe_659dc9_idx"
                    ),
                ],
                "unique_together": {("event", "member")},
            },
        ),
    ]
