# Generated by Django 4.2.11 on 2025-12-22 08:51
# Modified to use SeparateDatabaseAndState for model migration between apps

from django.db import migrations, models
import django.db.models.deletion
import layout.models.footer_content


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0003_footercontent"),
    ]

    operations = [
        # Use SeparateDatabaseAndState to tell Django these models exist in db
        # but need to be registered in the layout app's state
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.CreateModel(
            name="FooterContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name to identify this footer version",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Machine-readable key for this footer version",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        default=layout.models.footer_content.default_footer_content,
                        help_text="Structured JSON describing footer sections, links, and CTAs",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one footer can be active at a time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Footer Content",
                "verbose_name_plural": "Footer Contents",
                        "db_table": "pages_footercontent",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.SlugField(
                        help_text="Machine-readable name (e.g. 'main_nav', 'footer').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for admin display.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this menu's purpose.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
                        "db_table": "pages_menu",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MenuPageLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first).",
                    ),
                ),
                (
                    "custom_title",
                    models.CharField(
                        blank=True,
                        help_text="Override the page title for this menu (optional).",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "css_classes",
                    models.CharField(
                        blank=True,
                        help_text="Additional CSS classes for styling.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class name (e.g. 'fa-home' for FontAwesome).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to open the link in a new browser tab.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "menu",
                    models.ForeignKey(
                        help_text="The menu this link belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="layout.menu",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="The page being linked.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Page Link",
                "verbose_name_plural": "Menu Page Links",
                        "db_table": "pages_menupagelink",
                "ordering": ["menu", "order"],
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="pages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Pages included in this menu.",
                related_name="menus",
                through="layout.MenuPageLink",
                to="pages.page",
            ),
        ),
            ],
            database_operations=[],
        ),
        # Now add the index constraint (state only, table already has it)
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.AddIndex(
            model_name="menupagelink",
            index=models.Index(
                        fields=["menu", "order"], name="pages_menu_menu_id_c18fe0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="menupagelink",
            unique_together={("menu", "page")},
                ),
            ],
            database_operations=[],
        ),
    ]
