# Generated by Django 4.2.11 on 2025-12-22 08:53

from django.db import migrations, models
import layout.models.menu


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_remove_layout_models"),
        ("layout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="items",
            field=models.JSONField(
                default=layout.models.menu.default_menu_items,
                help_text="JSON array of menu items. Each item can be home, page, or external link.",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="pages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Legacy: Pages included in this menu.",
                related_name="menus",
                through="layout.MenuPageLink",
                to="pages.page",
            ),
        ),
    ]
