# Generated by Django 4.2.11 on 2025-12-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layout", "0002_add_items_jsonfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated from name if not provided.",
                max_length=200,
            ),
        ),
    ]
