from django.db import close_old_connections

from .approval_tools import (
    get_cms_page_detail,
    get_model_schema,
    get_record,
    list_database_models,
    propose_cms_page_update,
    propose_db_create,
    propose_db_delete,
    propose_db_update,
    search_records,
)
from .legacy import (
    count_members,
    get_campaign_stats,
    get_checkin_stats,
    get_event_registrations,
    get_page_views,
    run_custom_query,
    search_cms_pages,
    search_email_campaigns,
    search_events,
    search_members,
    search_news,
    search_projects,
    search_semesters,
)
from .registry import get_adk_tool_metadata, get_adk_tools

__all__ = [
    "close_old_connections",
    "count_members",
    "get_adk_tool_metadata",
    "get_adk_tools",
    "get_campaign_stats",
    "get_checkin_stats",
    "get_cms_page_detail",
    "get_event_registrations",
    "get_model_schema",
    "get_page_views",
    "get_record",
    "list_database_models",
    "propose_cms_page_update",
    "propose_db_create",
    "propose_db_delete",
    "propose_db_update",
    "run_custom_query",
    "search_cms_pages",
    "search_email_campaigns",
    "search_events",
    "search_members",
    "search_news",
    "search_projects",
    "search_records",
    "search_semesters",
]
