# Generated by Django 5.2.10 on 2026-05-26 07:56

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MiniApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "url_path",
                    models.CharField(
                        help_text="Frontend URL path, e.g. /news or /my-tool",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^/[a-z0-9][a-z0-9\\-/]*$",
                                "Must start with / and contain only lowercase, digits, hyphens, slashes.",
                            )
                        ],
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in API URLs: /miniapps/<slug>/...",
                        max_length=120,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Material icon name",
                        max_length=50,
                    ),
                ),
                (
                    "embeddable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this app can be rendered in /_embed/ iframes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "html_code",
                    models.TextField(blank=True, default="", verbose_name="HTML"),
                ),
                (
                    "js_code",
                    models.TextField(blank=True, default="", verbose_name="JavaScript"),
                ),
                (
                    "css_code",
                    models.TextField(blank=True, default="", verbose_name="CSS"),
                ),
            ],
            options={
                "verbose_name": "Mini App",
                "verbose_name_plural": "Mini Apps",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="MiniAppDataRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="miniapps.miniapp",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="miniapp_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Record",
                "verbose_name_plural": "Data Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MiniAppDataSchema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text='Array of field definitions: [{"name": "title", "type": "text", "required": true, "max_length": 200}]',
                    ),
                ),
                (
                    "app",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_schema",
                        to="miniapps.miniapp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Schema",
                "verbose_name_plural": "Data Schemas",
            },
        ),
        migrations.CreateModel(
            name="MiniAppVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("version_number", models.PositiveIntegerField()),
                ("html_code", models.TextField(blank=True, default="")),
                ("js_code", models.TextField(blank=True, default="")),
                ("css_code", models.TextField(blank=True, default="")),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="miniapps.miniapp",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="miniapp_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "App Version",
                "verbose_name_plural": "App Versions",
                "ordering": ["-version_number"],
                "unique_together": {("app", "version_number")},
            },
        ),
    ]
