# Generated by Django 5.2.10 on 2026-05-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miniapps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="miniapp",
            name="url_prefix_match",
            field=models.BooleanField(
                default=False,
                help_text="Match any path starting with url_path (e.g. /news also matches /news/123)",
            ),
        ),
    ]
