# Generated by Django 5.2.17 on 2026-10-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_intelligence", "0007_public_assistant_token_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemintelligenceconfig",
            name="public_assistant_global_token_limit",
            field=models.PositiveIntegerField(
                db_default=2000000,
                default=2000000,
                help_text="Spend ceiling, applied to EACH feature separately: the public assistant and the past-project AI search each have their own counter and may each consume up to this many tokens, for all users, in a 24-hour window (a feature's window opens with its first request after its previous window ended). When a feature reaches it, that feature answers 'usage limit reached' for everyone until its window ends or this value is raised (a change applies immediately); the other feature keeps working. Size it at 2x or more of the busiest expected day of the busier feature: people x questions x ~2,700 tokens per chat answer (up to ~7,300 with a full site context), or searches x ~15,000 tokens per AI search. Worst-case daily cost is about this value x the model's OUTPUT price per token, for each feature (so at most twice that for both). 0 switches off the model calls of both features.",
                verbose_name="Global Token Limit (per feature, per 24 hours)",
            ),
        ),
        migrations.AlterField(
            model_name="publicassistanttokenbudget",
            name="ip_hash",
            field=models.CharField(
                help_text="Opaque 64-hex budget key: a keyed hash of the visitor or member the budget belongs to, or the fixed key of one feature's global budget. Never an IP address or a raw id.",
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="systemintelligenceconfig",
            name="public_assistant_ip_token_limit",
            field=models.PositiveIntegerField(
                default=50000,
                help_text="Max tokens ONE visitor (anonymous browser) or ONE signed-in member may consume within the window, across the public assistant and past-project AI search. Not keyed on IP address. Requests from old cached pages without a visitor identity share one bucket that is exempt from this limit (it stands for many people at once; the public assistant's Global Token Limit and a request-rate limit bound it instead). A fairness limit only (visitor identities are free to obtain) -- the spend ceiling is the Global Token Limit. 0 disables this per-visitor/member limit.",
                verbose_name="Per-Visitor / Per-Member Token Limit",
            ),
        ),
        migrations.AlterField(
            model_name="systemintelligenceconfig",
            name="public_assistant_ip_token_window_seconds",
            field=models.PositiveIntegerField(
                default=86400,
                help_text="Window, in seconds, for the per-visitor/member token limit (default 24h).",
                verbose_name="Per-Visitor / Per-Member Token Window (seconds)",
            ),
        ),
    ]
