# Generated by Django 5.2.10 on 2026-03-26 07:07

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteMaintenanceControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_maintenance",
                    models.BooleanField(
                        default=False,
                        help_text="Enable to put the site into maintenance mode.",
                        verbose_name="Maintenance Mode",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="We are performing scheduled maintenance. Please try again shortly.",
                        help_text="Message displayed to users during maintenance.",
                        verbose_name="Maintenance Message",
                    ),
                ),
                (
                    "bypass_password",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Password that allows authorized users to bypass maintenance mode. Leave blank to disable bypass.",
                        max_length=128,
                        verbose_name="Bypass Password",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Maintenance Control",
                "verbose_name_plural": "Site Maintenance Control",
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField(db_index=True)),
                ("version_number", models.PositiveIntegerField(db_index=True)),
                (
                    "data",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-version_number"],
                        name="core_modelv_content_22aa92_idx",
                    )
                ],
                "unique_together": {("content_type", "object_id", "version_number")},
            },
        ),
    ]
