# Generated by Django 5.2.10 on 2026-02-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteMaintenanceControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_maintenance",
                    models.BooleanField(
                        default=False,
                        help_text="Enable to put the site into maintenance mode.",
                        verbose_name="Maintenance Mode",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="We are performing scheduled maintenance. Please try again shortly.",
                        help_text="Message displayed to users during maintenance.",
                        verbose_name="Maintenance Message",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Maintenance Control",
                "verbose_name_plural": "Site Maintenance Control",
            },
        ),
    ]
