# Generated by Django 5.2.12 on 2026-04-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsserviceconfig",
            name="from_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Twilio phone number for sending messages (e.g. +1234567890). Used for test SMS.",
                max_length=20,
                verbose_name="From Phone Number",
            ),
        ),
    ]
