# Generated by Django 5.2.12 on 2026-03-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailServiceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ses_access_key_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AWS access key for SES. Leave blank to skip SES and use SMTP only.",
                        max_length=128,
                        verbose_name="SES Access Key ID",
                    ),
                ),
                (
                    "ses_secret_access_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="SES Secret Access Key",
                    ),
                ),
                (
                    "ses_region",
                    models.CharField(
                        blank=True,
                        default="us-west-2",
                        max_length=32,
                        verbose_name="SES Region",
                    ),
                ),
                (
                    "ses_from_email",
                    models.CharField(
                        blank=True,
                        default="i2g@g.ucmerced.edu",
                        help_text="Sender email address for both SES and SMTP.",
                        max_length=254,
                        verbose_name="From Email",
                    ),
                ),
                (
                    "ses_from_name",
                    models.CharField(
                        blank=True,
                        default="Innovate to Grow",
                        max_length=128,
                        verbose_name="From Name",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True,
                        default="smtp.gmail.com",
                        max_length=254,
                        verbose_name="SMTP Host",
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(default=587, verbose_name="SMTP Port"),
                ),
                (
                    "smtp_use_tls",
                    models.BooleanField(default=True, verbose_name="SMTP Use TLS"),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="SMTP Username",
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="SMTP Password",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Service Config",
                "verbose_name_plural": "Email Service Config",
            },
        ),
        migrations.CreateModel(
            name="SMSServiceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_sid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Twilio Account SID (starts with AC).",
                        max_length=64,
                        verbose_name="Account SID",
                    ),
                ),
                (
                    "auth_token",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Auth Token"
                    ),
                ),
                (
                    "verify_sid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Twilio Verify Service SID (starts with VA).",
                        max_length=64,
                        verbose_name="Verify Service SID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SMS Service Config",
                "verbose_name_plural": "SMS Service Config",
            },
        ),
    ]
