# Generated by Django 5.2.10 on 2026-03-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_site_maintenance_control"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitemaintenancecontrol",
            name="bypass_password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Password that allows authorized users to bypass maintenance mode. Leave blank to disable bypass.",
                max_length=128,
                verbose_name="Bypass Password",
            ),
        ),
    ]
