# Generated by Django 5.2.12 on 2026-04-02 19:55

import core.models.base.service_credentials
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_smsserviceconfig_from_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCredentialConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Default",
                        help_text="A label to identify this configuration (e.g. 'Production Sheets', 'Dev Service Account').",
                        max_length=128,
                        verbose_name="Config Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one config can be active. Activating this will deactivate others.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "credentials_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Paste the full contents of the Google service-account JSON key file.",
                        validators=[
                            core.models.base.service_credentials.validate_google_credentials_json
                        ],
                        verbose_name="Service Account JSON",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Google Credential Config",
                "verbose_name_plural": "Google Credential Configs",
            },
        ),
    ]
