# Generated by Django 4.2.11 on 2025-12-28
import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authn", "0002_add_organization_field"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Barcode",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "time_created",
                            models.DateTimeField(
                                auto_now_add=True, null=True, verbose_name="time created"
                            ),
                        ),
                        (
                            "barcode_uuid",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                unique=True,
                                verbose_name="barcode uuid",
                            ),
                        ),
                        (
                            "barcode_type",
                            models.CharField(
                                choices=[
                                    ("CatCard Barcode", "CatCardBarcode"),
                                    ("Identification", "Identification"),
                                ],
                                max_length=255,
                                verbose_name="barcode type",
                            ),
                        ),
                        ("barcode", models.CharField(max_length=255, verbose_name="barcode")),
                        (
                            "profile_img",
                            models.TextField(
                                blank=True,
                                help_text="Base64 encoded PNG. No data-URL prefix",
                                null=True,
                            ),
                        ),
                        ("profile_information_id", models.TextField(blank=True, null=True)),
                        ("profile_name", models.TextField(blank=True, null=True)),
                        (
                            "model_user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "authn_barcode",
                        "verbose_name": "Barcode",
                        "verbose_name_plural": "Barcodes",
                        "ordering": ["-time_created"],
                    },
                ),
                migrations.CreateModel(
                    name="MobileID",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "user_mobile_id_server",
                            models.CharField(
                                default="i2g.ucmerced.edu",
                                max_length=255,
                                verbose_name="user mobile id server",
                            ),
                        ),
                        (
                            "model_user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "user_barcode",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="mobileid.barcode",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "authn_mobileid",
                        "verbose_name": "Mobile ID",
                        "verbose_name_plural": "Mobile IDs",
                    },
                ),
                migrations.CreateModel(
                    name="Transaction",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "time_used",
                            models.DateTimeField(
                                auto_now_add=True, null=True, verbose_name="time used"
                            ),
                        ),
                        (
                            "barcode_used",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="mobileid.barcode",
                            ),
                        ),
                        (
                            "model_user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "authn_transaction",
                        "verbose_name": "Transaction",
                        "verbose_name_plural": "Transactions",
                        "ordering": ["-time_used"],
                    },
                ),
            ],
        ),
    ]

