# Generated by Django 4.2.11 on 2026-01-10 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "barcode_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="barcode uuid",
                    ),
                ),
                (
                    "barcode_type",
                    models.CharField(
                        choices=[
                            ("CatCardBarcode", "CatCardBarcode"),
                            ("Identification", "Identification"),
                        ],
                        max_length=255,
                        verbose_name="barcode type",
                    ),
                ),
                ("barcode", models.CharField(max_length=255, verbose_name="barcode")),
                (
                    "profile_img",
                    models.TextField(
                        blank=True,
                        help_text="Base64 encoded PNG. No data-URL prefix",
                        null=True,
                    ),
                ),
                ("profile_information_id", models.TextField(blank=True, null=True)),
                ("profile_name", models.TextField(blank=True, null=True)),
                (
                    "model_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Barcode",
                "verbose_name_plural": "Barcodes",
                "db_table": "authn_barcode",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "barcode_used",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mobileid.barcode",
                    ),
                ),
                (
                    "model_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "authn_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MobileID",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "user_mobile_id_server",
                    models.CharField(
                        default="i2g.ucmerced.edu",
                        max_length=255,
                        verbose_name="user mobile id server",
                    ),
                ),
                (
                    "model_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_activate_barcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_activate_barcode",
                        to="mobileid.barcode",
                    ),
                ),
                (
                    "user_barcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mobileid.barcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile ID",
                "verbose_name_plural": "Mobile IDs",
                "db_table": "authn_mobileid",
            },
        ),
    ]
