# Generated by Django 5.2.12 on 2026-04-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cmsblock",
            name="version",
        ),
        migrations.RemoveField(
            model_name="cmspage",
            name="version",
        ),
        migrations.RemoveField(
            model_name="footercontent",
            name="version",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="version",
        ),
        migrations.RemoveField(
            model_name="newsarticle",
            name="version",
        ),
        migrations.RemoveField(
            model_name="newsfeedsource",
            name="version",
        ),
    ]
