# Generated by Django 5.2.10 on 2026-05-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0015_cmsembedwidget_schedule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsArticle",
        ),
        migrations.DeleteModel(
            name="NewsSyncLog",
        ),
        migrations.DeleteModel(
            name="NewsFeedSource",
        ),
    ]
