# Generated by Django 4.2.11 on 2025-12-22 08:13

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "member_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Member UUID",
                        unique=True,
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, help_text="Middle Name", max_length=255, null=True
                    ),
                ),
                (
                    "is_active_member",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user is an active member.",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ContactEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.EmailField(max_length=254, unique=True)),
                (
                    "ctype",
                    models.CharField(
                        choices=[
                            ("school", "School"),
                            ("work", "Work"),
                            ("personal", "Personal"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("subscribe", models.BooleanField(default=False)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Contact Phone Number (e.g. +1234567890)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("1", "United States"),
                            ("86", "China P.R.C."),
                            ("886", "Taiwan R.O.C."),
                        ],
                        help_text="Region of the phone number",
                        max_length=20,
                    ),
                ),
                ("subscribe", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact Phone",
                "verbose_name_plural": "Contact Phones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RSAKeypair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Key identifier (UUID).",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="site-signing",
                        help_text="Human friendly label for this keypair.",
                        max_length=255,
                    ),
                ),
                (
                    "public_key_pem",
                    models.TextField(help_text="Public key in PEM format."),
                ),
                (
                    "private_key_pem",
                    models.TextField(help_text="Private key in PEM format."),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this keypair is currently active.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "RSA Keypair",
                "verbose_name_plural": "RSA Keypairs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="I2GMemberGroup",
            fields=[],
            options={
                "verbose_name": "I2G Member Group",
                "verbose_name_plural": "I2G Member Groups",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.TextField(
                        blank=True,
                        help_text="User Display Name",
                        null=True,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "profile_image",
                    models.TextField(
                        blank=True,
                        help_text="User Profile Image, Base64 Encoded PNG 128*128",
                        null=True,
                        verbose_name="Profile Image (Base64 Encoded PNG)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authn.contactemail",
                    ),
                ),
                (
                    "contact_phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authn.contactphone",
                    ),
                ),
                (
                    "model_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
