# Generated by Django 5.2.10 on 2026-01-30 02:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSAKeypair",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "key_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Key identifier (UUID).",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="site-signing",
                        help_text="label for this keypair.",
                        max_length=255,
                    ),
                ),
                (
                    "public_key_pem",
                    models.TextField(blank=True, help_text="Public key in PEM format."),
                ),
                (
                    "private_key_pem",
                    models.TextField(
                        blank=True, help_text="Private key in PEM format."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this keypair is currently active.",
                    ),
                ),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "RSA Keypair",
                "verbose_name_plural": "RSA Keypairs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="I2GMemberGroup",
            fields=[],
            options={
                "verbose_name": "I2G Member Group",
                "verbose_name_plural": "I2G Member Groups",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="ContactEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Email address for contact",
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("other", "Other"),
                        ],
                        default="primary",
                        help_text="Type of email address",
                        max_length=255,
                        verbose_name="Email Type",
                    ),
                ),
                (
                    "subscribe",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the email is subscribed to communications",
                        verbose_name="Subscribed",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the email address has been verified",
                        verbose_name="Verified",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Email",
                "verbose_name_plural": "Contact Emails",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email_address"], name="authn_conta_email_a_6f580e_idx"
                    ),
                    models.Index(
                        fields=["email_type"], name="authn_conta_email_t_8a1be3_idx"
                    ),
                    models.Index(
                        fields=["verified"], name="authn_conta_verifie_dff1e7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, help_text="Middle Name", max_length=255, null=True
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization or company the member belongs to",
                        max_length=255,
                        null=True,
                        verbose_name="Organization",
                    ),
                ),
                (
                    "is_active_member",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user is an active member.",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "account_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authn.contactemail",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ContactPhone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Contact Phone Number (e.g. +1234567890)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("1-US", "United States"),
                            ("1-CA", "Canada"),
                            ("52", "Mexico"),
                            ("86", "China P.R.C."),
                            ("852", "Hong Kong S.A.R."),
                            ("853", "Macau S.A.R."),
                            ("886", "Taiwan R.O.C."),
                            ("81", "Japan"),
                            ("82", "South Korea"),
                            ("60", "Malaysia"),
                            ("62", "Indonesia"),
                            ("63", "Philippines"),
                            ("65", "Singapore"),
                            ("66", "Thailand"),
                            ("84", "Vietnam"),
                            ("91", "India"),
                            ("92", "Pakistan"),
                            ("94", "Sri Lanka"),
                            ("880", "Bangladesh"),
                            ("44", "United Kingdom"),
                            ("33", "France"),
                            ("49", "Germany"),
                            ("39", "Italy"),
                            ("34", "Spain"),
                            ("31", "Netherlands"),
                            ("46", "Sweden"),
                            ("47", "Norway"),
                            ("45", "Denmark"),
                            ("41", "Switzerland"),
                            ("43", "Austria"),
                            ("32", "Belgium"),
                            ("48", "Poland"),
                            ("420", "Czech Republic"),
                            ("972", "Israel"),
                            ("971", "United Arab Emirates"),
                            ("966", "Saudi Arabia"),
                            ("974", "Qatar"),
                            ("965", "Kuwait"),
                            ("968", "Oman"),
                            ("90", "Turkey"),
                            ("61", "Australia"),
                            ("64", "New Zealand"),
                            ("55", "Brazil"),
                            ("54", "Argentina"),
                            ("56", "Chile"),
                            ("57", "Colombia"),
                            ("51", "Peru"),
                            ("27", "South Africa"),
                            ("20", "Egypt"),
                            ("234", "Nigeria"),
                            ("254", "Kenya"),
                        ],
                        help_text="Region of the phone number",
                        max_length=20,
                    ),
                ),
                (
                    "subscribe",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the phone number is subscribed to communications",
                        verbose_name="Subscribed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Phone",
                "verbose_name_plural": "Contact Phones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number"], name="authn_conta_phone_n_a8a545_idx"
                    ),
                    models.Index(
                        fields=["region"], name="authn_conta_region_9e701d_idx"
                    ),
                    models.Index(
                        fields=["subscribe"], name="authn_conta_subscri_35b6d5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "display_name",
                    models.TextField(
                        blank=True,
                        help_text="User Display Name",
                        null=True,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "profile_image",
                    models.TextField(
                        blank=True,
                        help_text="User Profile Image, Base64 Encoded PNG 128*128",
                        null=True,
                        verbose_name="Profile Image (Base64 Encoded PNG)",
                    ),
                ),
                (
                    "model_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MemberContactInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "contact_email",
                    models.ForeignKey(
                        help_text="Contact email address",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_contact_infos",
                        to="authn.contactemail",
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.ForeignKey(
                        help_text="Contact phone number",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_contact_infos",
                        to="authn.contactphone",
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "model_user",
                    models.ForeignKey(
                        help_text="Member this contact information belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_infos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Contact Info",
                "verbose_name_plural": "Member Contact Infos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["model_user"], name="authn_membe_model_u_29946c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="authn_membe_created_527b33_idx"
                    ),
                ],
                "unique_together": {("model_user", "contact_email", "contact_phone")},
            },
        ),
    ]
