# Generated by Django 5.2.12 on 2026-04-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="member",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="member",
            name="username",
        ),
    ]
