# Generated by Django 5.2.12 on 2026-03-29 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="is_active_member",
        ),
    ]
