# Generated by Django 4.2.11 on 2025-12-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="organization",
            field=models.CharField(
                blank=True,
                help_text="Organization or company the member belongs to",
                max_length=255,
                null=True,
                verbose_name="Organization",
            ),
        ),
    ]
