# Generated by Django 5.2.10 on 2026-02-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberprofile",
            name="avatar",
        ),
    ]
