# Generated by Django 5.2.10 on 2026-02-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactphone",
            name="verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether the phone number has been verified",
                verbose_name="Verified",
            ),
        ),
        migrations.AddIndex(
            model_name="contactphone",
            index=models.Index(
                fields=["verified"], name="authn_conta_verifie_626d50_idx"
            ),
        ),
    ]
