# Generated by Django 5.2.12 on 2026-04-01 23:21

import authn.models.members.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0002_alter_member_managers_remove_member_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="member",
            managers=[
                ("objects", authn.models.members.manager.MemberManager()),
            ],
        ),
    ]
