# Generated by Django 4.2.11 on 2025-12-24 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0002_fix_contact_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="time created"
                    ),
                ),
                (
                    "barcode_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="barcode uuid",
                    ),
                ),
                (
                    "barcode_type",
                    models.CharField(
                        choices=[
                            ("CatCard Barcode", "CatCardBarcode"),
                            ("Identification", "Identification"),
                        ],
                        max_length=255,
                        verbose_name="barcode type",
                    ),
                ),
                ("barcode", models.CharField(max_length=255, verbose_name="barcode")),
                (
                    "profile_img",
                    models.TextField(
                        blank=True,
                        help_text="Base64 encoded PNG. No data-URL prefix",
                        null=True,
                    ),
                ),
                ("profile_information_id", models.TextField(blank=True, null=True)),
                ("profile_name", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Barcode",
                "verbose_name_plural": "Barcodes",
                "ordering": ["-time_created"],
            },
        ),
        migrations.CreateModel(
            name="MobileID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_mobile_id_server",
                    models.CharField(
                        default="i2g.ucmerced.edu",
                        max_length=255,
                        verbose_name="user mobile id server",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile ID",
                "verbose_name_plural": "Mobile IDs",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_used",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="time used"
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-time_used"],
            },
        ),
        migrations.AlterModelOptions(
            name="contactemail",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact Email",
                "verbose_name_plural": "Contact Emails",
            },
        ),
        migrations.AlterModelOptions(
            name="membercontactinfo",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Member Contact Info",
                "verbose_name_plural": "Member Contact Infos",
            },
        ),
        # Note: RemoveField create_at/ctype removed - 0002 already renamed them
        # Note: AddField email_type/verified removed - 0002 already handled them
        # AlterField to update email_type choices (ctype was renamed to email_type in 0002)
        migrations.AlterField(
            model_name="contactemail",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("other", "Other"),
                ],
                default="primary",
                help_text="Type of email address",
                max_length=255,
                verbose_name="Email Type",
            ),
        ),
        # Note: AddField updated_at to contactphone removed - 0002 already added it
        migrations.AddField(
            model_name="member",
            name="contect_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authn.contactemail",
            ),
        ),
        migrations.AlterField(
            model_name="contactemail",
            name="email_address",
            field=models.EmailField(
                help_text="Email address for contact",
                max_length=254,
                unique=True,
                verbose_name="Email Address",
            ),
        ),
        migrations.AlterField(
            model_name="contactemail",
            name="subscribe",
            field=models.BooleanField(
                default=False,
                help_text="Whether the email is subscribed to communications",
                verbose_name="Subscribed",
            ),
        ),
        migrations.AlterField(
            model_name="contactphone",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When this phone number was added",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="contactphone",
            name="region",
            field=models.CharField(
                choices=[
                    ("1-US", "United States"),
                    ("1-CA", "Canada"),
                    ("52", "Mexico"),
                    ("86", "China P.R.C."),
                    ("852", "Hong Kong S.A.R."),
                    ("853", "Macau S.A.R."),
                    ("886", "Taiwan R.O.C."),
                    ("81", "Japan"),
                    ("82", "South Korea"),
                    ("60", "Malaysia"),
                    ("62", "Indonesia"),
                    ("63", "Philippines"),
                    ("65", "Singapore"),
                    ("66", "Thailand"),
                    ("84", "Vietnam"),
                    ("91", "India"),
                    ("92", "Pakistan"),
                    ("94", "Sri Lanka"),
                    ("880", "Bangladesh"),
                    ("44", "United Kingdom"),
                    ("33", "France"),
                    ("49", "Germany"),
                    ("39", "Italy"),
                    ("34", "Spain"),
                    ("31", "Netherlands"),
                    ("46", "Sweden"),
                    ("47", "Norway"),
                    ("45", "Denmark"),
                    ("41", "Switzerland"),
                    ("43", "Austria"),
                    ("32", "Belgium"),
                    ("48", "Poland"),
                    ("420", "Czech Republic"),
                    ("972", "Israel"),
                    ("971", "United Arab Emirates"),
                    ("966", "Saudi Arabia"),
                    ("974", "Qatar"),
                    ("965", "Kuwait"),
                    ("968", "Oman"),
                    ("90", "Turkey"),
                    ("61", "Australia"),
                    ("64", "New Zealand"),
                    ("55", "Brazil"),
                    ("54", "Argentina"),
                    ("56", "Chile"),
                    ("57", "Colombia"),
                    ("51", "Peru"),
                    ("27", "South Africa"),
                    ("20", "Egypt"),
                    ("234", "Nigeria"),
                    ("254", "Kenya"),
                ],
                help_text="Region of the phone number",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contactphone",
            name="subscribe",
            field=models.BooleanField(
                default=False,
                help_text="Whether the phone number is subscribed to communications",
                verbose_name="Subscribed",
            ),
        ),
        migrations.AlterField(
            model_name="membercontactinfo",
            name="contact_email",
            field=models.ForeignKey(
                help_text="Contact email address",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_contact_infos",
                to="authn.contactemail",
                verbose_name="Contact Email",
            ),
        ),
        migrations.AlterField(
            model_name="membercontactinfo",
            name="contact_phone",
            field=models.ForeignKey(
                help_text="Contact phone number",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_contact_infos",
                to="authn.contactphone",
                verbose_name="Contact Phone",
            ),
        ),
        migrations.AlterField(
            model_name="membercontactinfo",
            name="model_user",
            field=models.ForeignKey(
                help_text="Member this contact information belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_infos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Member",
            ),
        ),
        migrations.AlterField(
            model_name="membercontactinfo",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When this contact information was last updated",
                verbose_name="Updated At",
            ),
        ),
        # Note: AlterUniqueTogether removed - 0002 already set it
        migrations.AddIndex(
            model_name="contactemail",
            index=models.Index(
                fields=["email_address"], name="authn_conta_email_a_6f580e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactemail",
            index=models.Index(
                fields=["email_type"], name="authn_conta_email_t_8a1be3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactemail",
            index=models.Index(
                fields=["verified"], name="authn_conta_verifie_dff1e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactphone",
            index=models.Index(
                fields=["phone_number"], name="authn_conta_phone_n_a8a545_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactphone",
            index=models.Index(fields=["region"], name="authn_conta_region_9e701d_idx"),
        ),
        migrations.AddIndex(
            model_name="contactphone",
            index=models.Index(
                fields=["subscribe"], name="authn_conta_subscri_35b6d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membercontactinfo",
            index=models.Index(
                fields=["model_user"], name="authn_membe_model_u_29946c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membercontactinfo",
            index=models.Index(
                fields=["created_at"], name="authn_membe_created_527b33_idx"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="barcode_used",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authn.barcode"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="model_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mobileid",
            name="model_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mobileid",
            name="user_barcode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authn.barcode"
            ),
        ),
        migrations.AddField(
            model_name="barcode",
            name="model_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
