# Generated by Django 5.2.10 on 2026-02-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0002_contactphone_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile picture.",
                null=True,
                upload_to="avatars/",
                verbose_name="Avatar",
            ),
        ),
    ]
