# Generated by Django 4.2.11 on 2025-12-28
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authn", "0002_add_organization_field"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="Transaction"),
                migrations.DeleteModel(name="MobileID"),
                migrations.DeleteModel(name="Barcode"),
            ],
        ),
    ]

