# Generated by Django 5.2.12 on 2026-03-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0002_remove_member_is_active_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admininvitation",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin")], default="admin", max_length=16
            ),
        ),
    ]
