# Generated by Django 5.2.10 on 2026-02-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0002_remove_avatar_from_memberprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberprofile",
            name="display_name",
        ),
    ]
