# Generated by Django 5.2.10 on 2026-02-24 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0003_remove_display_name_from_memberprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="account_email",
        ),
        migrations.AddField(
            model_name="contactemail",
            name="member",
            field=models.ForeignKey(
                blank=True,
                help_text="Member this email belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_emails",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Member",
            ),
        ),
        migrations.AddField(
            model_name="contactphone",
            name="member",
            field=models.ForeignKey(
                blank=True,
                help_text="Member this phone belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_phones",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Member",
            ),
        ),
        migrations.DeleteModel(
            name="MemberContactInfo",
        ),
    ]
