# Generated by Django 5.2.12 on 2026-04-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0003_alter_member_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admininvitation",
            name="version",
        ),
        migrations.RemoveField(
            model_name="contactemail",
            name="version",
        ),
        migrations.RemoveField(
            model_name="contactphone",
            name="version",
        ),
        migrations.RemoveField(
            model_name="emailauthchallenge",
            name="version",
        ),
        migrations.RemoveField(
            model_name="member",
            name="version",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="version",
        ),
        migrations.RemoveField(
            model_name="rsakeypair",
            name="version",
        ),
    ]
