# Generated by Django 4.2.27 on 2025-12-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0003_move_mobile_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rsakeypair",
            name="name",
            field=models.CharField(
                default="site-signing",
                help_text="label for this keypair.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="rsakeypair",
            name="private_key_pem",
            field=models.TextField(blank=True, help_text="Private key in PEM format."),
        ),
        migrations.AlterField(
            model_name="rsakeypair",
            name="public_key_pem",
            field=models.TextField(blank=True, help_text="Public key in PEM format."),
        ),
    ]
