# Generated by Django 4.2.27 on 2026-01-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0004_alter_rsakeypair_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="First name (optional)",
                        max_length=255,
                        null=True,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Last name (optional)",
                        max_length=255,
                        null=True,
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary email address",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "secondary_email",
                    models.EmailField(
                        blank=True,
                        help_text="Secondary email address (optional)",
                        max_length=254,
                        null=True,
                        verbose_name="Secondary Email",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Phone number (optional)",
                        max_length=20,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "when_input",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this prospect was first input",
                        verbose_name="When Input?",
                    ),
                ),
                (
                    "when_signed_up_as_member",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this prospect signed up as a member",
                        null=True,
                        verbose_name="When signed up as member?",
                    ),
                ),
                (
                    "when_last_checked",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this prospect was last checked",
                        verbose_name="When last checked?",
                    ),
                ),
                (
                    "primary_bounced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the primary email bounced",
                        null=True,
                        verbose_name="Bounced (when)?",
                    ),
                ),
                (
                    "primary_collision",
                    models.BooleanField(
                        default=False,
                        help_text="Whether primary email collides with existing member",
                        verbose_name="Collision?",
                    ),
                ),
                (
                    "secondary_bounced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the secondary email bounced",
                        null=True,
                        verbose_name="Secondary Bounced (when)?",
                    ),
                ),
                (
                    "secondary_collision",
                    models.BooleanField(
                        default=False,
                        help_text="Whether secondary email collides with existing member",
                        verbose_name="Secondary Collision",
                    ),
                ),
                (
                    "phone_bounced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the phone number bounced",
                        null=True,
                        verbose_name="Phone Bounced (when)?",
                    ),
                ),
                (
                    "phone_collision",
                    models.BooleanField(
                        default=False,
                        help_text="Whether phone number collides with existing member",
                        verbose_name="Phone Collision",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this prospect",
                        verbose_name="Notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prospect",
                "verbose_name_plural": "Prospects",
                "ordering": ["-when_input"],
            },
        ),
        migrations.AddField(
            model_name="contactemail",
            name="bounced",
            field=models.BooleanField(
                default=False,
                help_text="Whether the email has bounced",
                verbose_name="Bounced",
            ),
        ),
        migrations.AddField(
            model_name="contactemail",
            name="bounced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the email bounced",
                null=True,
                verbose_name="Bounced At",
            ),
        ),
        migrations.AddField(
            model_name="contactemail",
            name="expired",
            field=models.BooleanField(
                default=False,
                help_text="Whether the email has expired",
                verbose_name="Expired",
            ),
        ),
        migrations.AddField(
            model_name="contactemail",
            name="expired_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the email expired",
                null=True,
                verbose_name="Expired At",
            ),
        ),
        migrations.AddIndex(
            model_name="contactemail",
            index=models.Index(
                fields=["bounced"], name="authn_conta_bounced_2b20a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactemail",
            index=models.Index(
                fields=["expired"], name="authn_conta_expired_b96d51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(fields=["email"], name="authn_prosp_email_b3a529_idx"),
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(
                fields=["when_input"], name="authn_prosp_when_in_383a3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(
                fields=["when_signed_up_as_member"],
                name="authn_prosp_when_si_a259a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(
                fields=["primary_collision"], name="authn_prosp_primary_f0cf96_idx"
            ),
        ),
    ]
