# Generated by Django 5.2.10 on 2026-02-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0004_remove_member_account_email_contactemail_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="User display name shown in UI.",
                max_length=255,
                null=True,
                verbose_name="Display Name",
            ),
        ),
    ]
