# Generated by Django 5.2.12 on 2026-03-10 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authn", "0005_add_display_name_to_memberprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAuthChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("register", "Register"),
                            ("login", "Login"),
                            ("password_reset", "Password Reset"),
                            ("password_change", "Password Change"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "target_email",
                    models.EmailField(
                        help_text="Email address where the verification code was sent.",
                        max_length=254,
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="Hashed verification code.", max_length=255
                    ),
                ),
                (
                    "verification_token_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hashed token returned after a code is verified.",
                        max_length=255,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When the code or verification token expires."
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the verification code was successfully checked.",
                        null=True,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("consumed", "Consumed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time the code email was sent.",
                        null=True,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_auth_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["purpose", "target_email", "status"],
                        name="authn_email_purpose_dcb13a_idx",
                    ),
                    models.Index(
                        fields=["member", "purpose", "status"],
                        name="authn_email_member__7cb12d_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="authn_email_expires_8e33bc_idx"
                    ),
                ],
            },
        ),
    ]
