# Generated by Django 5.2.10 on 2026-03-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0006_emailauthchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="email_subscribe",
            field=models.BooleanField(
                default=True,
                help_text="Whether the member is subscribed to email communications.",
                verbose_name="Email Subscribe",
            ),
        ),
        migrations.AlterField(
            model_name="emailauthchallenge",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("login", "Login"),
                    ("password_reset", "Password Reset"),
                    ("password_change", "Password Change"),
                    ("contact_email_verify", "Contact Email Verify"),
                ],
                max_length=32,
            ),
        ),
    ]
