# Generated by Django 5.2.10 on 2026-03-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authn", "0008_admininvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailauthchallenge",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("login", "Login"),
                    ("password_reset", "Password Reset"),
                    ("password_change", "Password Change"),
                    ("contact_email_verify", "Contact Email Verify"),
                    ("admin_login", "Admin Login"),
                ],
                max_length=32,
            ),
        ),
    ]
