# Generated by Django 5.2.10 on 2026-03-21 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authn", "0010_emailsubscriber"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailSubscriber",
        ),
    ]
