# Generated by Django 5.2.10 on 2026-03-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0011_delete_emailsubscriber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberprofile",
            name="display_name",
        ),
    ]
